mutation CreateCustomerAccounts {
  ernie_checking: createAccount(
    input: {
      accountId: "1fd1dd3e-33fe-4ef5-9d58-676ef8d306b5"
      name: "Ernie Bishop - Checking"
      code: "ERNIE.CHECKING"
      description: "Ernie's checking account"
      normalBalanceType: CREDIT
    }
  ) {
    accountId
    name
  }

  bert_checking: createAccount(
    input: {
      accountId: "6c6affb0-5cf5-402b-8d84-01bfc1624a2c"
      name: "Bert - Checking"
      code: "BERT.CHECKING"
      description: "Bert's checking account"
      normalBalanceType: CREDIT
    }
  ) {
    accountId
    name
  }
}
