mutation MoneyFormatting {
  createJournal(
    input: { journalId: "26ae7ab3-e8c4-4828-9fbe-f03eea73ce0e", name: "GL", description: "General Ledger" }
  ) {
    journalId
  }

  createAccount(
    input: {
      accountId: "7b19df69-da47-4b69-b3ee-071efa89366c"
      code: "EXAMPLE_ACCT"
      name: "Example"
      description: "Example"
      normalBalanceType: CREDIT
      status: ACTIVE
    }
  ) {
    accountId
  }

  offset: createAccount(
    input: {
      accountId: "632492c4-0dd9-4766-83f5-3c13556dd488"
      code: "EXAMPLE_ACCT_OFFSET"
      name: "Example offset"
      description: "Example offset"
      normalBalanceType: CREDIT
      status: ACTIVE
    }
  ) {
    accountId
  }

  createTranCode(
    input: {
      tranCodeId: "e8cb44f3-2260-4281-8383-810596a7acf3"
      code: "FORMATTING_EXAMPLE"
      description: "Formatting Example"
      params: [
        { name: "amount", type: DECIMAL }
        { name: "currency", type: STRING }
      ]
      transaction: { journalId: "uuid('26ae7ab3-e8c4-4828-9fbe-f03eea73ce0e')", effective: "date('2022-01-01')" }
      entries: [
        {
          accountId: "uuid('7b19df69-da47-4b69-b3ee-071efa89366c')"
          units: "params.amount"
          currency: "params.currency"
          entryType: "'FORMATTING_EXAMPLE'"
          direction: "CREDIT"
          layer: "SETTLED"
        }
        {
          accountId: "uuid('632492c4-0dd9-4766-83f5-3c13556dd488')"
          units: "params.amount"
          currency: "params.currency"
          entryType: "'FORMATTING_EXAMPLE'"
          direction: "DEBIT"
          layer: "SETTLED"
        }
      ]
    }
  ) {
    tranCodeId
  }

  whole_num_example: postTransaction(input: {
    transactionId: "e63279d9-473d-4cc6-aad1-d6d3dbf15830"
    tranCode: "FORMATTING_EXAMPLE"
    params: {
      amount: "9"
      currency: "USD"
    }
  }
  ) {
    entries(first: 1) {
      nodes {
        amount {
          units
          currency
          us_std: formatted(as: {
            locale: "en-US"
          })
          no_dig: formatted(as: {
            locale: "en-US"
            maxDigits: 0
          })
        }
      }
    }
  }

  min_digits_example: postTransaction(input: {
    transactionId: "716fa9a8-3f79-41a7-9cf8-bc7d5c454c7f"
    tranCode: "FORMATTING_EXAMPLE"
    params: {
      amount: "9"
      currency: "USD"
    }
  }
  ) {
    entries(first: 1) {
      nodes {
        amount {
          units
          currency
          default: formatted(as: { locale: "en-US" })
          min_0: formatted(as: { locale: "en-US", minDigits: 0 })
          min_1: formatted(as: { locale: "en-US", minDigits: 1 })
          min_2: formatted(as: { locale: "en-US", minDigits: 2 })
          min_3: formatted(as: { locale: "en-US", minDigits: 3 })
        }
      }
    }
  }

  max_digits_example: postTransaction(input: {
    transactionId: "48a08d0e-a729-4cb7-ae6d-235dd6c8eb8c"
    tranCode: "FORMATTING_EXAMPLE"
    params: {
      amount: "9.123456789"
      currency: "USD"
    }
  }
  ) {
    entries(first: 1) {
      nodes {
        amount {
          units
          currency
          default: formatted(as: { locale: "en-US" })
          max_0: formatted(as: { locale: "en-US", maxDigits: 0 })
          max_1: formatted(as: { locale: "en-US", maxDigits: 1 })
          max_2: formatted(as: { locale: "en-US", maxDigits: 2 })
          max_3: formatted(as: { locale: "en-US", maxDigits: 3 })
        }
      }
    }
  }

  rounding_example_1: postTransaction(input: {
    transactionId: "470fb58e-2617-4d20-be51-9d42c8d830fd"
    tranCode: "FORMATTING_EXAMPLE"
    params: {
      amount: "9.005"
      currency: "USD"
    }
  }
  ) {
    entries(first: 1) {
      nodes {
        amount {
          units
          currency
          rd_down: formatted(as: {
            locale: "en-US"
            roundingMode: DOWN
            maxDigits: 2
          })
          rd_half_down: formatted(as: {
            locale: "en-US"
            roundingMode: HALF_DOWN
            maxDigits: 2
          })
          rd_up: formatted(as: {
            locale: "en-US"
            roundingMode: UP
            maxDigits: 2
          })
          rd_half_up: formatted(as: {
            locale: "en-US"
            roundingMode: HALF_UP
            maxDigits: 2
          })
        }
      }
    }
  }

  rounding_example_2: postTransaction(input: {
    transactionId: "a7e246eb-7911-4b5a-aaa1-ce940fc7f854"
    tranCode: "FORMATTING_EXAMPLE"
    params: {
      amount: "9.006"
      currency: "USD"
    }
  }
  ) {
    entries(first: 1) {
      nodes {
        amount {
          units
          currency
          rd_down: formatted(as: {
            locale: "en-US"
            roundingMode: DOWN
            maxDigits: 2
          })
          rd_half_down: formatted(as: {
            locale: "en-US"
            roundingMode: HALF_DOWN
            maxDigits: 2
          })
          rd_up: formatted(as: {
            locale: "en-US"
            roundingMode: UP
            maxDigits: 2
          })
          rd_half_up: formatted(as: {
            locale: "en-US"
            roundingMode: HALF_UP
            maxDigits: 2
          })
        }
      }
    }
  }

  locale_example_usd: postTransaction(input: {
    transactionId: "9681c2d9-e746-4dcd-8041-34e86d616cb5"
    tranCode: "FORMATTING_EXAMPLE"
    params: {
      amount: "123456789.123456789"
      currency: "USD"
    }
  }
  ) {
    entries(first: 1) {
      nodes {
        amount {
          units
          currency
          china: formatted(as: { locale: "zh-CN" })
          colombia: formatted(as: { locale: "es-CO" })
          france: formatted(as: { locale: "fr-FR" })
          germany: formatted(as: { locale: "de-DE" })
          india: formatted(as: { locale: "hi-IN" })
          japan: formatted(as: { locale: "ja-JP" })
          uae: formatted(as: { locale: "ar-AE" })
          uk: formatted(as: { locale: "en-GB" })
          usa: formatted(as: { locale: "en-US" })
        }
      }
    }
  }

  locale_example_eur: postTransaction(input: {
    transactionId: "2af1d012-bf51-43f8-b3b0-3dac9f2bfaa2"
    tranCode: "FORMATTING_EXAMPLE"
    params: {
      amount: "123456789.123456789"
      currency: "EUR"
    }
  }
  ) {
    entries(first: 1) {
      nodes {
        amount {
          units
          currency
          china: formatted(as: { locale: "zh-CN" })
          colombia: formatted(as: { locale: "es-CO" })
          france: formatted(as: { locale: "fr-FR" })
          germany: formatted(as: { locale: "de-DE" })
          india: formatted(as: { locale: "hi-IN" })
          japan: formatted(as: { locale: "ja-JP" })
          uae: formatted(as: { locale: "ar-AE" })
          uk: formatted(as: { locale: "en-GB" })
          usa: formatted(as: { locale: "en-US" })
        }
      }
    }
  }

  grouping_example: postTransaction(input: {
    transactionId: "c15b617f-d1c8-4e1f-933a-b0ee349b44f7"
    tranCode: "FORMATTING_EXAMPLE"
    params: {
      amount: "123456789.123456789"
      currency: "USD"
    }
  }
  ) {
    entries(first: 1) {
      nodes {
        amount {
          units
          currency
          china: formatted(as: { locale: "zh-CN", groupDigits: true })
          colombia: formatted(as: { locale: "es-CO", groupDigits: true })
          france: formatted(as: { locale: "fr-FR", groupDigits: true })
          germany: formatted(as: { locale: "de-DE", groupDigits: true })
          india: formatted(as: { locale: "hi-IN", groupDigits: true })
          japan: formatted(as: { locale: "ja-JP", groupDigits: true })
          uae: formatted(as: { locale: "ar-AE", groupDigits: true })
          uk: formatted(as: { locale: "en-GB", groupDigits: true })
          usa: formatted(as: { locale: "en-US", groupDigits: true })
        }
      }
    }
  }

  currency_min_digits_example_usd: postTransaction(input: {
    transactionId: "280004be-fb13-489e-9c13-79926daf2074"
    tranCode: "FORMATTING_EXAMPLE"
    params: {
      amount: "9.00"
      currency: "USD" # US Dollar, 2 minor units
    }
  }
  ) {
    entries(first: 1) {
      nodes {
        amount {
          units
          currency
          formatted(as: { locale: "en-US" })
        }
      }
    }
  }

  currency_min_digits_example_ugx: postTransaction(input: {
    transactionId: "6379d1cf-7b05-499f-8b9d-9f0bcf1f956b"
    tranCode: "FORMATTING_EXAMPLE"
    params: {
      amount: "9"
      currency: "UGX" # Uganda Shilling, 0 minor units
    }
  }
  ) {
    entries(first: 1) {
      nodes {
        amount {
          units
          currency
          formatted(as: { locale: "en-US" })
        }
      }
    }
  }

  currency_min_digits_example_jod: postTransaction(input: {
    transactionId: "8ca6708f-fbee-4595-ac7d-8c31aa14803c"
    tranCode: "FORMATTING_EXAMPLE"
    params: {
      amount: "9"
      currency: "JOD" # Jordanian Dinar, 3 minor units
    }
  }
  ) {
    entries(first: 1) {
      nodes {
        amount {
          units
          currency
          formatted(as: { locale: "en-US" })
        }
      }
    }
  }

  currency_display_example_usd: postTransaction(input: {
    transactionId: "3972000c-41d4-4f5b-89de-dc5e4eef98d9"
    tranCode: "FORMATTING_EXAMPLE"
    params: {
      amount: "12345.67"
      currency: "USD"
    }
  }
  ) {
    entries(first: 1) {
      nodes {
        amount {
          units
          currency
          default: formatted(as: { locale: "en-US" })
          code: formatted(as: { locale: "en-US", currencyDisplay: CODE })
          none: formatted(as: { locale: "en-US", currencyDisplay: NONE })
          symbol: formatted(as: { locale: "en-US", currencyDisplay: SYMBOL })
        }
      }
    }
  }
}
