mutation AllocateBudgets(
  $bertBudgetId: UUID!
  $bertCheckingId: UUID!
  $ernieBudgetId: UUID!
  $settlementCheckingId: UUID!
) {
  allocateBudgetForBert: postTransaction(
    input: {
      tranCode: "ALLOC_BUDGET"
      transactionId: "6403c5e0-9ee9-4ac4-ab2d-b05a2264c3e6"
      params: {
        account: $bertBudgetId
        amount: "40"
        effective: "2022-11-10"
        category: "Discretionary Spending"
      }
    }
  ) {
    transactionId
  }

  allocateBudgetForErnie: postTransaction(
    input: {
      tranCode: "ALLOC_BUDGET"
      transactionId: "f62cbecf-3826-4eae-95db-cc45b313e1a8"
      params: {
        account: $ernieBudgetId
        amount: "200"
        effective: "2022-11-09"
        category: "Expenses"
      }
    }
  ) {
    transactionId
  }

  recordVenmoPaymentBert: postTransaction(
    input: {
      tranCode: "RECORD_TX"
      transactionId: "1b76219c-31cc-4776-9fa0-546b6ffe8c27"
      params: {
        account: $bertCheckingId
        settlementAccount: $settlementCheckingId
        amount: "44.82"
        effective: "2022-11-07"
        transactionType: "Venmo payment"
        isDebit: "false"
      }
    }
  ) {
    transactionId
  }

  assignVenmoToBudgetBert: postTransaction(
    input: {
      tranCode: "ASSIGN_TO_BUDGET"
      transactionId: "95d5b790-d709-4f41-8361-43029b3e1af3"
      params: {
        account: $bertBudgetId,
        amount: "44.82"
        effective: "2022-11-07"
        category: "Food"
      }
    }
  ) {
    transactionId
  }
}
