query GetCustomersBalances($customersId: UUID!, $journalId: UUID!) {
  accountSet(id: $customersId) {
    name
    balance {
      settled {
        normalBalance {
          units
        }
      }
    }
    members(first: 10) {
      nodes {
        __typename
        ... on Account {
          name
          balance(journalId: $journalId) {
            settled {
              normalBalance {
                units
              }
            }
          }
        }
      }
    }
  }
}
