mutation MultiJournalSetup {
  j1: createJournal(
    input: {
      journalId: "41ee64d6-dcde-46dc-bdc5-c9164517402a"
      name: "Journal 1"
      description: "Primary journal"
    }
  ) {
    journalId
  }

  j2: createJournal(
    input: {
      journalId: "2d9355ac-1844-4378-8fae-7ccb104e98c9"
      name: "Journal 2"
      description: "Secondary journal"
    }
  ) {
    journalId
  }

  acct_set_1: createAccountSet(
    input: {
      accountSetId: "861f2709-5e62-4a97-8364-b4d3b0a3b31f"
      journalId: "41ee64d6-dcde-46dc-bdc5-c9164517402a"
      name: "Accounts"
      description: "Group entries in all accounts for primary journal"
      normalBalanceType: CREDIT
    }
  ) {
    accountSetId
    normalBalanceType
  }

  acct_set_2: createAccountSet(
    input: {
      accountSetId: "c21f202f-d92d-48e5-aaf0-d48865a98051"
      journalId: "2d9355ac-1844-4378-8fae-7ccb104e98c9"
      name: "Accounts"
      description: "Group entries in all accounts for secondary journal"
      normalBalanceType: CREDIT
    }
  ) {
    accountSetId
    normalBalanceType
  }

  acct_a: createAccount(
    input: {
      accountId: "80c06296-7afb-4725-8cdd-57c2ce881af2"
      code: "ACCT_A"
      name: "Account A"
      description: "Account A"
      normalBalanceType: CREDIT
      status: ACTIVE
      accountSetIds: [
        "861f2709-5e62-4a97-8364-b4d3b0a3b31f"
        "c21f202f-d92d-48e5-aaf0-d48865a98051"
      ]
    }
  ) {
    accountId
    sets(first: 4) {
      nodes {
        accountSetId
        normalBalanceType
      }
    }
  }

  acct_b: createAccount(
    input: {
      accountId: "6d808949-437f-4f23-a345-b09225104808"
      code: "ACCT_B"
      name: "Account B"
      description: "Account B"
      normalBalanceType: CREDIT
      status: ACTIVE
      accountSetIds: [
        "861f2709-5e62-4a97-8364-b4d3b0a3b31f"
        "c21f202f-d92d-48e5-aaf0-d48865a98051"
      ]
    }
  ) {
    accountId
    sets(first: 4) {
      nodes {
        accountSetId
        normalBalanceType
      }
    }
  }

  xfr: createTranCode(
    input: {
      tranCodeId: "8f50f1be-a6c5-4f42-a623-57db9ff9f543"
      code: "XFR"
      description: "Transfer money."
      params: [
        { name: "effectiveDate", type: DATE }
        { name: "amount", type: DECIMAL }
        {
          name: "fromAccount"
          type: UUID
          description: "Account to send funds from."
        }
        {
          name: "toAccount"
          type: UUID
          description: "Recipient account. Required."
        }
        { name: "journal", type: UUID, description: "Journal ID. Required." }
      ]
      transaction: {
        journalId: "params.journal"
        effective: "params.effectiveDate"
      }
      entries: [
        {
          accountId: "params.fromAccount"
          units: "params.amount"
          currency: "'USD'"
          entryType: "'XFR_DR'"
          direction: "DEBIT"
          layer: "SETTLED"
        }
        {
          accountId: "params.toAccount"
          units: "params.amount"
          currency: "'USD'"
          entryType: "'XFR_CR'"
          direction: "CREDIT"
          layer: "SETTLED"
        }
      ]
    }
  ) {
    tranCodeId
  }
}
