query GetEntries {
  entries(
    index: { name: TRANSACTION_ID }
    where: { transactionId: { eq: "114a8b1e-d00b-4e13-ab27-ec3472622c0a" } }
    first: 10
  ) {
    nodes {
      entryType
      account {
        name
      }
      direction
      amount {
        units
        currency
      }
    }
  }
}
