query GetAuthClient($authClientGithub: String!) {
  auth {
    client(principal: $authClientGithub) {
      principal
      name
      policies {
        effect
        actions
        resources
      }
    }
  }
}
