mutation PostLithicWebhook {
  cards {
    postLithicTransaction(input:{
        accountId: "1fd1dd3e-33fe-4ef5-9d58-676ef8d306b5"
        journalId: "822cb59f-ce51-4837-8391-2af3b7a5fc51"
        webhook: {
          status: "AUTHORIZATION",
          amount: 100,
          acquirer_fee: 0,
          authorization_amount: 100,
          settled_amount: 0,
          events: [],
          created: "2022-10-01T00:00:00Z",
          token: "2f05a4d4-07c5-42c1-a567-438737b7a0ad"
        }
    }) {
      transaction{
        transactionId
        metadata
      }
      balance{
        settled:available(layer: SETTLED) {
          normalBalance {
            units
            currency
          }
        }
        available:available(layer:PENDING){
          normalBalance {
            units
            currency
          }
        }
      }
    }
  }
}
