query GetAccountSets {
  accountSets(
    index: { name: NAME }
    where: { name: { like: "" }, journalId: { eq: "822cb59f-ce51-4837-8391-2af3b7a5fc51" } }
    first: 10
  ) {
    nodes {
      accountSetId
      name
      description
    }
  }
}
