mutation SetupPositionLedger(
  $journalId: UUID!
  $journalIdExpr: Expression!
  $brokerRevenue: UUID!
  $brokerRevenueExpr: Expression!
  $brokerSettlement: UUID!
  $brokerSettlementExpr: Expression!
  $brokerInvestment: UUID!
  $brokerInvestmentExpr: Expression!
  $brokerHoldings: UUID!
  $brokerHoldingsExpr: Expression!
  $clientACash: UUID!
  $clientAInvestment: UUID!
  $clientADividendRev: UUID!
  $clientAHoldings: UUID!
  $clientBCash: UUID!
  $clientBInvestment: UUID!
  $clientBDividendRev: UUID!
  $clientBHoldings: UUID!
) {
  gl: createJournal(input: { journalId: $journalId, name: "GL", description: "General Ledger" }) {
    journalId
  }

  brokerAccts: createAccountSet(
    input: {
      accountSetId: "96c0402a-29d5-4811-98a4-2e2270d58805"
      journalId: $journalId
      name: "Broker Accounts"
      description: "All accounts for Broker"
      normalBalanceType: CREDIT
    }
  ) {
    accountSetId
  }

  aliciaAccts: createAccountSet(
    input: {
      accountSetId: "60c3c770-18c1-4d66-8e9a-8e06852e11c6"
      journalId: $journalId
      name: "Alicia Accounts"
      description: "All accounts for Alicia"
      normalBalanceType: CREDIT
    }
  ) {
    accountSetId
  }

  bobbyAccts: createAccountSet(
    input: {
      accountSetId: "dc6b7f03-8e0a-45a4-a348-cb280c28f0a9"
      journalId: $journalId
      name: "Bobby Accounts"
      description: "All accounts for Bobby"
      normalBalanceType: CREDIT
    }
  ) {
    accountSetId
  }

  # BROKER.REVENUE - (revenue) credit-normal
  brokerRevenueAcct: createAccount(
    input: {
      accountId: $brokerRevenue
      code: "BROKER.REVENUE"
      name: "Broker_Revenue"
      description: "_Revenue Account For Broker"
      normalBalanceType: CREDIT
      status: ACTIVE
      accountSetIds: ["96c0402a-29d5-4811-98a4-2e2270d58805"]
    }
  ) {
    accountId
  }
  # BROKER.SETTLEMENT - (asset) debit-normal
  brokerSettlementAcct: createAccount(
    input: {
      accountId: $brokerSettlement
      code: "BROKER.SETTLEMENT"
      name: "Broker_Settlement"
      description: "_Settlement Account For Broker"
      normalBalanceType: DEBIT
      status: ACTIVE
      accountSetIds: ["96c0402a-29d5-4811-98a4-2e2270d58805"]
    }
  ) {
    accountId
  }
  # BROKER.INVESTMENT - (equity) credit-normal
  brokerInvestmentAcct: createAccount(
    input: {
      accountId: $brokerInvestment
      code: "BROKER.INVESTMENT"
      name: "Broker_Investment"
      description: "_Investment Account For Broker"
      normalBalanceType: CREDIT
      status: ACTIVE
      accountSetIds: ["96c0402a-29d5-4811-98a4-2e2270d58805"]
    }
  ) {
    accountId
  }
  # BROKER.HOLDINGS - (asset) debit-normal
  brokerHoldingsAcct: createAccount(
    input: {
      accountId: $brokerHoldings
      code: "BROKER.HOLDINGS"
      name: "Broker_Holdings"
      description: "_Holdings Account For Broker"
      normalBalanceType: DEBIT
      status: ACTIVE
      accountSetIds: ["96c0402a-29d5-4811-98a4-2e2270d58805"]
    }
  ) {
    accountId
  }

  # CLIENT_A_CASH - (asset) debit-normal
  clientACashAcct: createAccount(
    input: {
      accountId: $clientACash
      code: "CLIENT_A.CASH"
      name: "Client A : Cash"
      description: "Cash account for Alicia"
      normalBalanceType: DEBIT
      status: ACTIVE
      accountSetIds: ["60c3c770-18c1-4d66-8e9a-8e06852e11c6"]
    }
  ) {
    accountId
  }
  # CLIENT_A.INVESTMENT - (equity) credit-normal
  clientAInvestmentAcct: createAccount(
    input: {
      accountId: $clientAInvestment
      code: "CLIENT_A.INVESTMENT"
      name: "Client A : Investment"
      description: "Investment account for Alicia"
      normalBalanceType: CREDIT
      status: ACTIVE
      accountSetIds: ["60c3c770-18c1-4d66-8e9a-8e06852e11c6"]
    }
  ) {
    accountId
  }
  # CLIENT_A.DIVIDEND_REV - (equity) credit-normal
  clientADividendRevAcct: createAccount(
    input: {
      accountId: $clientADividendRev
      code: "CLIENT_A.DIVIDEND_REV"
      name: "Client A : Dividends"
      description: "Dividend revenue account for Alicia"
      normalBalanceType: CREDIT
      status: ACTIVE
      accountSetIds: ["60c3c770-18c1-4d66-8e9a-8e06852e11c6"]
    }
  ) {
    accountId
  }
  # CLIENT_A.HOLDINGS - (asset) debit-normal
  clientAHoldingsAcct: createAccount(
    input: {
      accountId: $clientAHoldings
      code: "CLIENT_A.HOLDINGS"
      name: "Client A : Holdings"
      description: "Holdings account for Alicia"
      normalBalanceType: DEBIT
      status: ACTIVE
      accountSetIds: ["60c3c770-18c1-4d66-8e9a-8e06852e11c6"]
    }
  ) {
    accountId
  }

  # CLIENT_B.CASH - (asset) debit-normal
  clientBCashAcct: createAccount(
    input: {
      accountId: $clientBCash
      code: "CLIENT_B.CASH"
      name: "Client B : Cash"
      description: "Cash account for Bobby"
      normalBalanceType: DEBIT
      status: ACTIVE
      accountSetIds: ["dc6b7f03-8e0a-45a4-a348-cb280c28f0a9"]
    }
  ) {
    accountId
  }
  # CLIENT_B.INVESTMENT - (equity) credit-normal
  clientBInvestmentAcct: createAccount(
    input: {
      accountId: $clientBInvestment
      code: "CLIENT_B.INVESTMENT"
      name: "Client B : Investment"
      description: "Investment account for Bobby"
      normalBalanceType: CREDIT
      status: ACTIVE
      accountSetIds: ["dc6b7f03-8e0a-45a4-a348-cb280c28f0a9"]
    }
  ) {
    accountId
  }
  # CLIENT_B.DIVIDEND_REV - (equity) credit-normal
  clientBDividendRevAcct: createAccount(
    input: {
      accountId: $clientBDividendRev
      code: "CLIENT_B.DIVIDEND_REV"
      name: "Client B : Dividends"
      description: "Dividend revenue account for Bobby"
      normalBalanceType: CREDIT
      status: ACTIVE
      accountSetIds: ["dc6b7f03-8e0a-45a4-a348-cb280c28f0a9"]
    }
  ) {
    accountId
  }
  # CLIENT_B.HOLDINGS - (asset) debit-normal
  clientBHoldingsAcct: createAccount(
    input: {
      accountId: $clientBHoldings
      code: "CLIENT_B_HOLDINGS"
      name: "Client B : Holdings"
      description: "Holdings account for Bobby"
      normalBalanceType: DEBIT
      status: ACTIVE
      accountSetIds: ["dc6b7f03-8e0a-45a4-a348-cb280c28f0a9"]
    }
  ) {
    accountId
  }

  buySecurityTC: createTranCode(
    input: {
      tranCodeId: "19e7f93e-40c6-42bd-a7b5-ef83ecf5ad8d"
      code: "BUY_SECURITY"
      description: "Buy shares in a security for a price and fee."
      params: [
        { name: "effective", type: DATE }
        { name: "clientHoldingsAcct", type: UUID }
        { name: "clientInvestAcct", type: UUID }
        { name: "clientCashAcct", type: UUID }
        {
          name: "security"
          type: STRING
          description: "Symbol of security to buy, e.g. `AAPL` or `MSFT`."
        }
        { name: "shares", type: DECIMAL, description: "Number of shares." }
        { name: "price", type: DECIMAL, description: "Price in USD per share." }
        {
          name: "feeRate"
          type: DECIMAL
          default: 0.0
          description: "Fee expressed as a decimal, so a 1.5% fee => 0.015."
        }
      ]
      transaction: {
        journalId: $journalIdExpr
        effective: "params.effective"
        description: "'Buy ' + string(params.shares) + ' ' + params.security + ' @ $' + string(params.price) + ' per share with a ' + string(params.feeRate) + ' brokerage fee.'"
      }
      entries: [
        {
          accountId: "params.clientCashAcct"
          units: "decimal.Mul(decimal.Mul(params.shares, params.price), decimal.Add(decimal('1'), params.feeRate))"
          currency: "'USD'"
          direction: "CREDIT"
          layer: "SETTLED"
          entryType: "'BUY_SECURITY_PAYMENT_CR'"
        }
        {
          accountId: "params.clientInvestAcct"
          units: "decimal.Mul(decimal.Mul(params.shares, params.price), decimal.Add(decimal('1'), params.feeRate))"
          currency: "'USD'"
          direction: "DEBIT"
          layer: "SETTLED"
          entryType: "'BUY_SECURITY_PAYMENT_DR'"
        }
        {
          accountId: $brokerRevenueExpr
          units: "decimal.Mul(params.shares, params.price)"
          currency: "'USD'"
          direction: "CREDIT"
          layer: "SETTLED"
          entryType: "'BUY_SECURITY_BROKER_EARNINGS_CR'"
        }
        {
          accountId: $brokerRevenueExpr
          units: "decimal.Mul(decimal.Mul(params.shares, params.price), params.feeRate)"
          currency: "'USD'"
          direction: "CREDIT"
          layer: "SETTLED"
          entryType: "'BUY_SECURITY_BROKER_FEE_CR'"
        }
        {
          accountId: $brokerSettlementExpr
          units: "decimal.Mul(decimal.Mul(params.shares, params.price), decimal.Add(decimal('1'), params.feeRate))"
          currency: "'USD'"
          direction: "DEBIT"
          layer: "SETTLED"
          entryType: "'BUY_SECURITY_BROKER_EARNINGS_DR'"
        }
        {
          accountId: $brokerHoldingsExpr
          units: "params.shares"
          currency: "params.security"
          direction: "CREDIT"
          layer: "SETTLED"
          entryType: "'BUY_SECURITY_TRADE_CR'"
        }
        {
          accountId: "params.clientHoldingsAcct"
          units: "params.shares"
          currency: "params.security"
          direction: "DEBIT"
          layer: "SETTLED"
          entryType: "'BUY_SECURITY_TRADE_DR'"
        }
      ]
    }
  ) {
    tranCodeId
  }

  sellSecurityTC: createTranCode(
    input: {
      tranCodeId: "01c9c437-78cd-4186-b03a-a033bc0daf87"
      code: "SELL_SECURITY"
      description: "Sell shares in a security for a price and fee."
      params: [
        { name: "effective", type: DATE }
        { name: "clientHoldingsAcct", type: UUID }
        { name: "clientInvestAcct", type: UUID }
        { name: "clientCashAcct", type: UUID }
        {
          name: "security"
          type: STRING
          description: "Symbol of security to sell, e.g. `AAPL` or `MSFT`."
        }
        { name: "shares", type: DECIMAL, description: "Number of shares." }
        { name: "price", type: DECIMAL, description: "Price in USD per share." }
        {
          name: "originalShareCost"
          type: DECIMAL
          description: "Price at which shares were originally purchased, including fee."
        }
        {
          name: "feeRate"
          type: DECIMAL
          default: 0.0
          description: "Fee expressed as a decimal, so a 1.5% fee => 0.015."
        }
      ]
      transaction: {
        journalId: $journalIdExpr
        effective: "params.effective"
        description: "'Sell ' + string(params.shares) + ' ' + params.security + ' @ $' + string(params.price) + ' per share with a ' + string(params.feeRate) + ' brokerage fee. Calculate gain/loss using an original share cost of $' + string(params.originalShareCost) + ' per share.'"
      }
      entries: [
        {
          accountId: "params.clientHoldingsAcct"
          units: "params.shares"
          currency: "params.security"
          direction: "CREDIT"
          layer: "SETTLED"
          entryType: "'SELL_SECURITY_TRADE_CR'"
        }
        {
          accountId: $brokerHoldingsExpr
          units: "params.shares"
          currency: "params.security"
          direction: "DEBIT"
          layer: "SETTLED"
          entryType: "'SELL_SECURITY_TRADE_DR'"
        }
        {
          accountId: "params.clientInvestAcct"
          units: "decimal.Mul(params.shares, params.originalShareCost)"
          currency: "'USD'"
          direction: "CREDIT"
          layer: "SETTLED"
          entryType: "'SELL_SECURITY_CLIENT_EARNINGS_CR'"
        }
        {
          accountId: "params.clientInvestAcct"
          units: "decimal.Sub(decimal.Mul(decimal.Mul(params.shares, params.price), decimal.Sub(decimal('1'), params.feeRate)), decimal.Mul(params.shares, params.originalShareCost))"
          currency: "'USD'"
          direction: "CREDIT"
          layer: "SETTLED"
          entryType: "'SELL_SECURITY_CLIENT_GAIN_LOSS_CR'"
        }
        {
          accountId: "params.clientCashAcct"
          units: "decimal.Mul(decimal.Mul(params.shares, params.price), decimal.Sub(decimal('1'), params.feeRate))"
          currency: "'USD'"
          direction: "DEBIT"
          layer: "SETTLED"
          entryType: "'SELL_SECURITY_CLIENT_EARNINGS_DR'"
        }
        {
          accountId: $brokerSettlementExpr
          units: "decimal.Mul(params.shares, params.price)"
          currency: "'USD'"
          direction: "CREDIT"
          layer: "SETTLED"
          entryType: "'SELL_SECURITY_BROKER_PAYMENT_CR'"
        }
        {
          accountId: $brokerInvestmentExpr
          units: "decimal.Mul(params.shares, params.price)"
          currency: "'USD'"
          direction: "DEBIT"
          layer: "SETTLED"
          entryType: "'SELL_SECURITY_BROKER_PAYMENT_DR'"
        }
        {
          accountId: $brokerRevenueExpr
          units: "decimal.Mul(decimal.Mul(params.shares, params.price), params.feeRate)"
          currency: "'USD'"
          direction: "CREDIT"
          layer: "SETTLED"
          entryType: "'SELL_SECURITY_BROKER_FEE_CR'"
        }
        {
          accountId: $brokerSettlementExpr
          units: "decimal.Mul(decimal.Mul(params.shares, params.price), params.feeRate)"
          currency: "'USD'"
          direction: "DEBIT"
          layer: "SETTLED"
          entryType: "'SELL_SECURITY_BROKER_FEE_DR'"
        }
      ]
    }
  ) {
    tranCodeId
  }

  earnDividendsTC: createTranCode(
    input: {
      tranCodeId: "fc1c5a32-7fbd-4fc4-b0ec-5d93cbad217c"
      code: "EARN_DIVIDENDS"
      description: "Earn dividends on an owned security."
      params: [
        { name: "effective", type: DATE }
        { name: "clientCashAcct", type: UUID }
        { name: "clientDividendRevAcct", type: UUID }
        {
          name: "security"
          type: STRING
          description: "Symbol of security, e.g. `AAPL` or `MSFT`."
        }
        { name: "shares", type: DECIMAL, description: "Number of shares." }
        { name: "dividendsPerShare", type: DECIMAL }
      ]
      transaction: {
        journalId: $journalIdExpr
        effective: "params.effective"
        description: "'Earn $' + string(params.dividendsPerShare) + ' dividends per share of ' + params.security + ' stock.'"
      }
      entries: [
        {
          accountId: "params.clientCashAcct"
          units: "decimal.Mul(params.shares, params.dividendsPerShare)"
          currency: "'USD'"
          direction: "DEBIT"
          layer: "SETTLED"
          entryType: "'EARN_DIVIDEND_DR'"
        }
        {
          accountId: "params.clientDividendRevAcct"
          units: "decimal.Mul(params.shares, params.dividendsPerShare)"
          currency: "'USD'"
          direction: "CREDIT"
          layer: "SETTLED"
          entryType: "'EARN_DIVIDEND_CR'"
        }
      ]
    }
  ) {
    tranCodeId
  }
}
