mutation ExchangeCurrencyTXs($exchangerAcctId: UUID!) {
  usd_to_inr: postTransaction(
    input: {
      transactionId: "73abdb88-4d7c-49e1-8581-2ecca3bdcc11"
      tranCode: "FX"
      params: {
        effective: "2022-10-12"
        account: $exchangerAcctId
        sellUnits: "1234.56"
        sellCurrency: "USD"
        buyCurrency: "INR"
        exchangeRate: "82.26"
      }
    }
  ) {
    transactionId
    entries(first: 10) {
      nodes {
        direction
        amount {
          units
          currency
          us_fmt: formatted(
            as: { locale: "en-US", groupDigits: true, maxDigits: 2 }
          )
          ind_fmt: formatted(
            as: { locale: "hi-IN", groupDigits: true, maxDigits: 2 }
          )
        }
      }
    }
  }

  usd_to_yen: postTransaction(
    input: {
      transactionId: "1dfc9913-d704-421b-a9f3-8c5fdb00913b"
      tranCode: "FX"
      params: {
        effective: "2022-10-12"
        account: $exchangerAcctId
        sellUnits: "567.89"
        sellCurrency: "USD"
        buyCurrency: "JPY"
        exchangeRate: "146.85"
      }
    }
  ) {
    transactionId
    entries(first: 10) {
      nodes {
        direction
        amount {
          units
          currency
          us_fmt: formatted(
            as: { locale: "en-US", groupDigits: true, maxDigits: 2 }
          )
          jpy_fmt: formatted(as: { locale: "ja-JP", groupDigits: true })
        }
      }
    }
  }

  inr_to_yen: postTransaction(
    input: {
      transactionId: "2d94227e-a617-47d0-8617-311c6993885f"
      tranCode: "FX"
      params: {
        effective: "2022-10-12"
        account: $exchangerAcctId
        sellUnits: "9876.54"
        sellCurrency: "INR"
        buyCurrency: "JPY"
        exchangeRate: "1.79"
      }
    }
  ) {
    transactionId
    entries(first: 10) {
      nodes {
        direction
        amount {
          units
          currency
          ind_fmt: formatted(
            as: { locale: "hi-IN", groupDigits: true, maxDigits: 2 }
          )
          jpy_fmt: formatted(as: { locale: "ja-JP", groupDigits: true })
        }
      }
    }
  }
}
