# TODO: Update graphql api to not require the id input on create mutations. Instead we should be able to auto-generate those.

extend type Mutation {
  "Mutations in the `admin` namespace are used to manage the organization data like users, groups, and tenants."
  admin: AdminMutation!
}

extend type Query {
  "Queries in the `admin` namespace retrieve organization data like users, groups, and tenants."
  admin: AdminQuery!
}

type AdminMutation {
  "Create a new group."
  createGroup("Fields to create a new group." input: CreateGroupInput!): Group
    @goField(forceResolver: true)

  # TODO: doesn't this mutation need the group's ID as an argument?
  "Update an existing group. To ensure data integrity, only a subset of fields are allowed."
  updateGroup("Fields to update." input: UpdateGroupInput!): Group @goField(forceResolver: true)

  "Delete an existing group."
  deleteGroup("Name of group to delete." name: String!): Group @goField(forceResolver: true)

  """
  Create a new human user.

  Upon creation, new users will receive an invite email to sign in to Twisp Console.
  """
  createUser("Fields to create a new user." input: CreateUserInput!): User
    @goField(forceResolver: true)

  # TODO: doesn't this mutation need the user's ID as an argument?
  "Update an existing human user. To ensure data integrity, only a subset of fields are allowed."
  updateUser("Fields to update." input: UpdateUserInput!): User @goField(forceResolver: true)

  "Delete an existing human user."
  deleteUser("Email of user to delete." email: String!): User @goField(forceResolver: true)

  "Create a new tenant."
  createTenant("Fields to create a new tenant." input: CreateTenantInput!): Tenant
    @goField(forceResolver: true)

  # TODO: doesn't this mutation need the tenants's ID as an argument?
  "Update an existing tenant. To ensure data integrity, only a subset of fields are allowed."
  updateTenant("Fields to update." input: UpdateTenantInput!): Tenant @goField(forceResolver: true)

  "Delete an existing tenant."
  deleteTenant("Unique identifier." accountId: String!): Tenant @goField(forceResolver: true)

  "Restore a tenant/region into a new tenant/region"
  restore(input: RestoreInput!): RestoreOutput @goField(forceResolver: true)
}

type AdminQuery {
  "Get the current organization."
  organization: Organization! @goField(forceResolver: true)

  "Get the list of tenants, ordered by `accountId`."
  tenants(
    "Number of nodes to return on the connection."
    first: Int!
    "Cursor indicating the start point to retrieve nodes. When no cursor is provided, the query uses the default starting cursor."
    after: String
  ): TenantConnection! @goField(forceResolver: true)

  "Get the list of groups, ordered by `name`."
  groups(
    "Number of nodes to return on the connection."
    first: Int!
    "Cursor indicating the start point to retrieve nodes. When no cursor is provided, the query uses the default starting cursor."
    after: String
  ): GroupConnection! @goField(forceResolver: true)

  "Get the list of human users, ordered by `email`."
  users(
    "Number of nodes to return on the connection."
    first: Int!
    "Cursor indicating the start point to retrieve nodes. When no cursor is provided, the query uses the default starting cursor."
    after: String
  ): UserConnection! @goField(forceResolver: true)

  """
  Retrieves the read and write usage units on per day basis. The metrics returned are on the half open interval.

  @example({"start": "2025-06-01", "end":"2025-07-01"}) returns metris `period >= 2025-06-01T00:00:00.000Z && period < 2025-07-01T00:00:00.000Z`
  """
  usage(input: UsageInput!): Usage @goField(forceResolver: true)
  """
  Retrieves the status of a restoration.
  """
  restoreStatus(executionId: UUID!): RestoreStatus @goField(forceResolver: true)
}

"""
Grouping of users within an organization.

Groups are used to manage access control and permissions for users. Each group can have one or more associated policies that define the allowed actions for its member users.

Users can belong to multiple groups, and their permissions are determined by the combined set of policies from all their groups.
"""
type Group {
  "Unique ID for the group."
  id: UUID!

  "The unique identifier of the organization to which the group belongs."
  organizationId: UUID!

  "A human-friendly name for the group, such as 'Admins' or 'DataAnalysts'."
  name: String!

  "A brief description of the group's purpose, intended to provide additional context."
  description: String!

  """
  A set of policies as a JSON list that define the permissions granted to users within this group.

  The structure of these policies matches the Policy type, but serialized as a JSON string.

  Example:

  ```
  policy: "[{\"actions\": [\"*\"],\"effect\": \"DENY\",\"resources\":[\"*\"],\"assertions\": {\"always false\": \"1 == 0\"}}]"
  ```
  """
  policy: String!

  "The current version number of this group. Updates will increment the version."
  version: Int!

  _recordId: UUID!
}

input CreateGroupInput {
  "Unique ID for the group."
  id: UUID!

  "A human-friendly name for the group, such as 'Admins' or 'DataAnalysts'."
  name: String!

  "A brief description of the group's purpose, intended to provide additional context."
  description: String!

  """
  A set of policies to apply to this group, formatted as a JSON list that define the permissions granted to users within this group.

  The structure of these policies matches the Policy type, but serialized as a JSON string.

  Example:

  ```
  policy: "[{\"actions\": [\"*\"],\"effect\": \"DENY\",\"resources\":[\"*\"],\"assertions\": {\"always false\": \"1 == 0\"}}]"
  ```
  """
  policy: String!
}

input UpdateGroupInput {
  "A human-friendly name for the group, such as 'Admins' or 'DataAnalysts'."
  name: String!

  "A brief description of the group's purpose, intended to provide additional context."
  description: String

  """
  A set of policies to apply to this group, formatted as a JSON list that define the permissions granted to users within this group.

  Valid actions include `db:Insert`, `db:Update`, `db:Delete`, `db:Select` or wildcard `*`

  Example:

  ```
  policy: "[{\"actions\": [\"*\"],\"effect\": \"DENY\",\"resources\":[\"*\"],\"assertions\": {\"always false\": \"1 == 0\"}}]"
  ```
  """
  policy: String
}

"""
Connection to a list of Group nodes.
Access Group nodes directly through the `nodes` field, or access information about the connection edges with the `edges` field.
Use `pageInfo` to paginate responses using the cursors provided.
"""
type GroupConnection implements Connection {
  nodes: [Group]!
  edges: [GroupConnectionEdge]!
  pageInfo: PageInfo!
}

"""
Edges represent links connecting a parent or query field to a list of Group nodes.
They contain a reference to the Group node and metadata like the `cursor` position for the edge.
"""
type GroupConnectionEdge {
  "Cursor position at this edge."
  cursor: String!
  "Reference to the Group node at this edge."
  node: Group
}

"""
The organization associated with the auth context.

Organizations have many tenants, groups, and users.
"""
type Organization {
  "Unique ID for the organization."
  id: UUID!

  "Name of the organization."
  name: String!

  "Description of the organization."
  description: String!

  "The current version number of this organization."
  version: Int!

  _recordId: UUID!
}

"""
A human user within the organization.

Users can belong to multiple groups, which define their permissions within the organization based on the associated policies of each group.

The user's effective permissions are determined by the combined set of policies from all their groups.

A user is uniquely identified by their email address.
"""
type User {
  "Unique ID for the user."
  id: UUID!

  "ID of the user's parent organization."
  organizationId: UUID!

  "A list of unique identifiers for the groups to which the user belongs. The user's permissions are determined by the combined policies of these groups."
  groupIds: [UUID!]!

  "The user's email address, which serves as a unique identifier and primary means of contact."
  email: String!

  "The current version number of this user. Updates will increment the version."
  version: Int!

  """
  Returns if the users MFA is enabled.
  """
  mfaEnabled: Boolean! @goField(forceResolver: true)

  # subject: UUID! "subject is currently a reserved field and should not be exposed to users"

  _recordId: UUID!
}

input CreateUserInput {
  "Unique ID for the user."
  id: UUID!

  "A list of unique identifiers for the groups to which the user belongs. The user's permissions are determined by the combined policies of these groups."
  groupIds: [UUID!]!

  "The user's email address, which serves as a unique identifier and primary means of contact."
  email: String!

  # subject: UUID! "subject is currently a reserved field and should not be exposed to users"
}

input UpdateUserInput {
  "A list of unique identifiers for the groups to which the user belongs. The user's permissions are determined by the combined policies of these groups."
  groupIds: [UUID!]

  "The user's email address, which serves as a unique identifier and primary means of contact."
  email: String!
}

"""
Connection to a list of User nodes.
Access User nodes directly through the `nodes` field, or access information about the connection edges with the `edges` field.
Use `pageInfo` to paginate responses using the cursors provided.
"""
type UserConnection implements Connection {
  nodes: [User]!
  edges: [UserConnectionEdge]!
  pageInfo: PageInfo!
}

"""
Edges represent links connecting a parent or query field to a list of User nodes.
They contain a reference to the User node and metadata like the `cursor` position for the edge.
"""
type UserConnectionEdge {
  "Cursor position at this edge."
  cursor: String!
  "Reference to the User node at this edge."
  node: User
}

"""
A Tenant represents an environment within an organization, typically associated with a specific application, service, or set of resources. Tenants contain isolated ledgers, each deployed to a specific region.

Tenants are useful for isolating data and configurations between different environments. Each tenant is uniquely identified by an accountId, which in combination with an AWS region, is used to calculate the database tenant for data isolation purposes.
"""
type Tenant {
  "Unique ID for the tenant."
  id: UUID!

  "ID of the tenant's parent organization."
  organizationId: UUID!

  """
  A globally unique identifier representing an environment within the organization.

  This accountId, when combined with an AWS region, is used to calculate the database tenant.
  """
  accountId: String!

  "A human-friendly name for the tenant, used for display purposes and easier identification."
  name: String!

  "A brief description of the tenant, providing additional context about its purpose or characteristics."
  description: String!

  "The current version number of this tenant. Updates will increment the version."
  version: Int!

  _recordId: UUID!
}

input CreateTenantInput {
  "Unique ID for the tenant."
  id: UUID!

  """
  A globally unique identifier representing an environment within the organization.

  This accountId, when combined with an AWS region, is used to calculate the database tenant.
  """
  accountId: String!

  "A human-friendly name for the tenant, used for display purposes and easier identification."
  name: String!

  "A brief description of the tenant, providing additional context about its purpose or characteristics."
  description: String!
}

input UpdateTenantInput {
  """
  A globally unique identifier representing an environment within the organization.

  This accountId, when combined with an AWS region, is used to calculate the database tenant.
  """
  accountId: String!

  "A human-friendly name for the tenant, used for display purposes and easier identification."
  name: String

  "A brief description of the tenant, providing additional context about its purpose or characteristics."
  description: String
}

"""
Connection to a list of Tenant nodes.
Access Tenant nodes directly through the `nodes` field, or access information about the connection edges with the `edges` field.
Use `pageInfo` to paginate responses using the cursors provided.
"""
type TenantConnection implements Connection {
  nodes: [Tenant]!
  edges: [TenantConnectionEdge]!
  pageInfo: PageInfo!
}

"""
Edges represent links connecting a parent or query field to a list of Tenant nodes.
They contain a reference to the Tenant node and metadata like the `cursor` position for the edge.
"""
type TenantConnectionEdge {
  "Cursor position at this edge."
  cursor: String!
  "Reference to the Tenant node at this edge."
  node: Tenant
}

enum ExcludeTableEnum {
  Account
  AccountContext
  AccountSet
  AccountSetMember
  AttachedCalculation
  Balance
  BulkExecution
  Calculation
  Endpoint
  Entry
  Journal
  Transaction
  TransactionException
  TranCode
  VelocityControl
  VelocityControlAccount
  VelocityLimit
  WorkflowExecution
}

input RestoreInput {
  """
  The region in the current tenant to restore from.
  """
  from_region: String!
  """
  The region in the target `tenant` to restore to.
  """
  to_region: String!
  """
  The target tenant to create for restoration.
  """
  tenant: CreateTenantInput!
  """
  List of tables to exclude from restoration.
  """
  excludeTables: [ExcludeTableEnum!]
  """
  Timestamp, up to 35 days in the past, to indicate from what time to export.
  """
  exportTime: Timestamp
  """
  List of glob patterns for files to include in restoration.
  By default no files are restored. Must supply patterns to restore files.
  Example: ["*.json"] includes all top level json files.
  """
  includeFileGlobs: [String!]
}

type RestoreOutput {
  execution_id: UUID!
}

input UsageInput {
  """
  Start date at midnight UTC.
  """
  start: Date!
  """
  End date at midnight UTC.
  """
  end: Date!
}

type Usage {
  """
  The number of read units in the period listed.
  """
  readUnits: [UsageDatum]
  """
  The number of write units in the period listed.
  """
  writeUnits: [UsageDatum]
  """
  The number of RPU seconds charged.
  Twisp bills per hour so divide `warehouseRPUSeconds.units / 3600` for billing purposes.
  """
  warehouseRPUSeconds: [UsageDatum]
}

type UsageDatum {
  period: Date
  units: Int
}

enum RestoreStatusEnum {
  EXPORTING
  IMPORTING
  COMPLETE
  ERROR
}

type RestoreStatus {
  executionId: UUID!
  status: RestoreStatusEnum!
  error: String
}
