extend type Mutation {
  "Mutations in the `auth` namespace are used to manage clients and their policies. Use the `createClient` mutation to create a new client, `updateClient` to update an existing client, and `deleteClient` to delete a client."
  auth: AuthMutation!
}

extend type Query {
  "Queries in the `auth` namespace are used to retrieve clients and their policies. Use the `client` query to retrieve a single client, and `clients` to retrieve a list of clients."
  auth: AuthQuery!
}

type AuthMutation {
  "Create a new security client."
  createClient(input: CreateClientInput!): Client! @goField(forceResolver: true)

  "Update an existing client by replacing policies."
  updateClient(
    "Principal of the client to update."
    principal: String!
    "Client fields to update."
    input: UpdateClientInput!
  ): Client @goField(forceResolver: true)

  "Delete a security client."
  deleteClient("Principal to delete.", principal: String!): Client @goField(forceResolver: true)
}

type AuthQuery {
  "Get a single client by the `principal`."
  client(
    "Principal of the client."
    principal: String!
  ): Client @goField(forceResolver: true)

  "Lists all clients."
  clients(
    "Number of nodes to return on the connection."
    first: Int!
    "Cursor indicating the start point to retrieve nodes. When no cursor is provided, the query uses the default starting cursor."
    after: String
  ): ClientConnection! @goField(forceResolver: true)
}

"""
Connection to a list of Client nodes.
Access Client nodes directly through the `nodes` field, or access information about the connection edges with the `edges` field.
Use `pageInfo` to paginate responses using the cursors provided.
"""
type ClientConnection implements Connection {
  nodes: [Client]!
  edges: [ClientConnectionEdge]!
  pageInfo: PageInfo!
}

"""
Edges represent links connecting a parent or query field to a list of Client nodes.
They contain a reference to the Client node and metadata like the `cursor` position for the edge.
"""
type ClientConnectionEdge {
  "Cursor position at this edge."
  cursor: String!
  "Reference to the Client node at this edge."
  node: Client
}

input CreateClientInput {
  """
  Principal that this client applies to.
  If you're supplying your own OIDC this will be the `iss` claim on your JWT.
  If using Twisp IAM/OIDC token exchange, this will be the IAM principal you signed with, typically a role ARN.
  """
  principal: String!

  "Unique name of the client."
  name: String!

  "The policies to evaluate."
  policies: [PolicyInput]!
}

input UpdateClientInput {
  "Replaces the existing policies with this new set of policies."
  policies: [PolicyInput]!
}

type Client implements Node {
  """
  Globally unique identifier for a record to support Global Object Identification.
  Uses format `cl:<key>` where `key` is the `base64(json({ 1: principal }))`
  """
  id: ID!

  """
  Principal that this client applies to.
  If you're supplying your own OIDC this will be the `iss` claim on your JWT.
  If using Twisp IAM/OIDC token exchange, this will be the IAM principal you signed with, typically a role ARN.
  """
  principal: String!

  "Unique name of the client."
  name: String!

  "The policies to evaluate."
  policies: [Policy]!
}

input PolicyInput {
  "Whether this Policy is an `ALLOW` or `DENY`."
  effect: PolicyEffect!

  """
  The set of actions to allow or deny.
  """
  actions: [PolicyAction]!

  """
  The resources to allow or deny.
  In the format `<namespace>.<resource>`

  The following namespaces exist:
  - `financial`
  - `tenancy`
  - `public`
  - `system`

  As do the following resources in the financial namespace:

  - `Account`
  - `AccountSet`
  - `AccountSetMember`
  - `Transaction`
  - `Entry`
  - `Balance`
  - `TranCode`
  - `Journal`

  You can use `*` to wildcard as well.
  """
  resources: [String]!

  """
  A map of expressions to evaluate this policy with.
  """
  assertions: ExpressionMap
}

type Policy {
  "Whether this Policy is an `ALLOW` or `DENY`."
  effect: PolicyEffect!

  """
  The set of actions to allow or deny."
  """
  actions: [PolicyAction]!

  """
  The resources to allow or deny.
  """
  resources: [String]!

  """
  A map of expressions to evaluate this policy with.
  """
  assertions: ExpressionMap
}

type PolicyAssertion {
  name: String!
  value: Expression!
}

enum PolicyAction {
  SELECT,
  INSERT,
  UPDATE,
  DELETE
}

enum PolicyEffect {
  ALLOW
  DENY
}
