extend type Query {
  "Mutations in the `events` namespace are used to manage event subscriptions, such as webhooks."
  events: EventsQuery!
}

extend type Mutation {
  "Queries in the `events` namespace retrieve event data, such as webhooks."
  events: EventsMutation!
}

type EventsQuery {
  "Get a single endpoint by it's `endpointId`"
  endpoint(
    id: UUID!
  ): Endpoint @goField(forceResolver: true)

  "Select one or more endpoints. Specify the index to use and apply filters to your query."
  endpoints(
    """
    Select from a list of pre-defined indexes. For optimal performance, choose specific indexes on unique fields over more general ones.
    """
    index: EndpointIndexInput!
    """
    Filter the query according to specified conditions. Depending on the index chosen, different filters will be allowed.
    """
    where: EndpointFilterInput!
    "Number of nodes to return on the connection."
    first: Int!
    "Cursor indicating the start point to retrieve nodes. When no cursor is provided, the query uses the default starting cursor."
    after: String
  ): EndpointConnection! @goField(forceResolver: true)
}

type EventsMutation {
  "Create a new endpoint."
  createEndpoint("Fields to create a new endpoint." input: EndpointInput!): Endpoint! @goField(forceResolver: true)

  "Update fields on an existing account. To ensure data integrity, only a subset of fields are allowed."
  updateEndpoint(
    "Unique identifier."
    id: UUID!
    "Fields to update."
    input: EndpointUpdateInput!
  ): Endpoint @goField(forceResolver: true)

  deleteEndpoint("Unique identifier." id: UUID!): Endpoint @goField(forceResolver: true)
}

type Endpoint implements Node {
  """
  Globally unique identifier for a record to support Global Object Identification.
  Uses format `ep:<key>` where `key` is `base64(json({ 1: endpointId }))`.
  """
  id: ID!
  "Unique identifier for the endpoint."
  endpointId: UUID!
  "Current status for the endpoint."
  status: EndpointStatus!
  "The type of endpoint this represents."
  endpointType: EndpointType!
  "The url for the endpoint. e.g.  https://yourdomain.com/path/to/hooks"
  url: String!
  "The events this is subscribed to."
  subscription: [String!]!
  "Description of this endpoint."
  description: String!
  "The secret Twisp will use to sign payloads with via HMAC/SHA256."
  signingSecret: String!
  """
  Map of named CEL expressions specifying conditions for sending an event to the endpoint.

  Record is only sent if _all_ expressions evaluate to true, i.e. they are combined with a logical AND. Each expression must return a boolean value.
  """
  filters: ExpressionMap
  "When this endpoint was created."
  created: Timestamp!
  "When this endpoint was last updated."
  modified: Timestamp!
  "The current version of the endpoint."
  version: Int!

  _recordId: UUID!
}

type EndpointConnection implements Connection {
  nodes: [Endpoint]!
  edges: [EndpointConnectionEdge]!
  pageInfo: PageInfo!
}

type EndpointConnectionEdge {
  cursor: String!

  node: Endpoint
}

input EndpointIndexInput {
  name: EndpointIndex!
  sort: SortOrder
}

enum EndpointIndex {
  "Index by `endpointId` field. Must supply an `endpointId: { eq: <id> }` filter to the `where` object."
  ENDPOINT_ID
  "Index by `status` field. Must supply an  `status: { eq: <status> }` filter to the `where` object."
  STATUS
}

input EndpointFilterInput {
  "Filter on the `endpointId` field. Required when using index `EndpointInded.ENDPOINT_ID`."
  endpointId: FilterValue
  "Filter on the `status` field. Only available when using index `EndpointIndex.STATUS`."
  status: FilterValue
}

"Fields to create a new endpoint."
input EndpointInput {
  "Unique identifier for the endpoint."
  endpointId: UUID!
  "Current status of the endpoint."
  status: EndpointStatus = ENABLED
  "The type of endpoint this endpoint is."
  endpointType: EndpointType = WEBHOOK
  "The url where this endpoint will transmit subscribed events to."
  url: String!
  """
  A list of subscriptions that are available, supporting wildcards `*`.

  Format: `<entity>.<inserted|updated|deleted>`
  Supported entities:
  - journal
  - account
  - accountcontext
  - accountset
  - accountsetmember
  - trancode
  - transaction
  - entry
  - balance
  - customindex
  - custombalance
  - endpoint
  """
  subscription: [String!]!
  "description of this endpoint."
  description: String!
  """
  Map of named CEL expressions specifying conditions for sending an event to the endpoint.

  Record is only sent if _all_ expressions evaluate to true, i.e. they are combined with a logical AND. Each expression must return a boolean value.
  """
  filters: ExpressionMap
}

"Fields to update an existing endpoint."
input EndpointUpdateInput {
  "Current status of the endpoint."
  status: EndpointStatus
  "The type of endpoint this endpoint is."
  endpointType: EndpointType
  "The url where this endpoint will transmit subscribed events to."
  url: String
  """
  A list of subscriptions that are available, supporting wildcards `*`.

  Format: `<entity>.<created|updated|deleted>`
  Supported entities:
  - journal
  - account
  - accountcontext
  - accountset
  - accountsetmember
  - trancode
  - transaction
  - entry
  - balance
  - customindex
  - custombalance
  - endpoint
  """
  subscription: [String]
  "description of this endpoint."
  description: String
  """
  Map of named CEL expressions specifying conditions for sending an event to the endpoint.

  Record is only sent if _all_ expressions evaluate to true, i.e. they are combined with a logical AND. Each expression must return a boolean value.
  """
  filters: ExpressionMap
}

enum EndpointStatus {
  ENABLED
  DISABLED
}

enum EndpointType {
  WEBHOOK
  ACH_PROCESSOR
}
