extend type Mutation {
  files: FilesMutation!
}

extend type Query {
  files: FilesQuery!
}

type FilesMutation {
  "Create a file upload."
  createUpload(input: CreateUpload!): Upload @goField(forceResolver: true)
  "Create a link to download a file."
  createDownload(key: String!): Download @goField(forceResolver: true)
}

type FilesQuery {
  list(keyPrefix: String!): [String!] @goField(forceResolver: true)
}

type Download {
  "Unique identifier of file. e.g. `path/to/file.json`"
  key: String!
  "Presigned URL for downloading the file."
  downloadURL: String!
  "Timestamp of when presigned url expires."
  downloadURLExpiration: Timestamp!
  "Headers to include in the upload request."
  downloadHeaders: JSON!
  "`Content-Type` of the file."
  contentType: String!
}

type Upload {
  "Unique identifier of file. e.g. `path/to/file.json`"
  key: String!
  "Presigned URL for uploading the actual file."
  uploadURL: String!
  "Timestamp of when presigned url expires. If expired before file uploaded will need to create new upload."
  uploadURLExpiration: Timestamp!
  "Headers to include in the upload request."
  uploadHeaders: JSON!
  """
  `contentType` of file. Currently only type supported is `application/json`. File should be array of json objects to pass
  to bulk query as variables, each item in array representing a single
  execution of the query.
  """
  contentType: String!
}

input CreateUpload {
  "Unique identifier of file. e.g. `path/to/file.json`"
  key: String!
  """
  The type of upload:
  `BULK_GRAPHQL_VARIABLES` - The content-type is `application/json` and is an array of json objects for a bulk graphql query execution.
  `ACH` - The content-type is `text/plain` and is a NACHA formatted text file.
  """
  uploadType: UploadType! = BULK_GRAPHQL_VARIABLES
  """
  `contentType` of file.
  """
  contentType: String!
}

enum UploadType {
  BULK_GRAPHQL_VARIABLES
  ACH
}
