extend type Query {
  "Get a single journal by its `journalId`. If `journalId` is omitted, return the default journal."
  journal("Unique identifier." id: UUID): Journal

  "Select one or more journals. Specify the index to use and apply filters to your query."
  journals(
    """
    Select from a list of pre-defined indexes. For optimal performance, choose specific indexes on unique fields over more general ones.
    """
    index: JournalIndexInput!
    """
    Filter the query according to specified conditions. Depending on the index chosen, different filters will be allowed.
    """
    where: JournalFilterInput
    "Number of nodes to return on the connection."
    first: Int!
    "Cursor indicating the start point to retrieve nodes. When no cursor is provided, the query uses the default starting cursor."
    after: String
  ): JournalConnection!
}

extend type Mutation {
  "Create a new journal for recording transactions in the ledger."
  createJournal(input: JournalInput!): Journal!

  "Update an existing journal. To ensure data integrity, only a subset of fields are allowed."
  updateJournal("Unique identifier." id: UUID!, input: JournalUpdateInput!): Journal!

  "Moves journal into `LOCKED` status. Prevents entries from being posted to the journal."
  deleteJournal("Unique identifier." id: UUID!): Journal
}

"""
Journals allow for the organizing of transactions within separate "books".

In many cases, users only need a single journal. For this reason, Twisp always contains a default journal with code `DEFAULT`.

Journals can be used for a variety of functions. For example, users may create separate journals for different currencies, or product-specific journals.
"""
type Journal implements Node{
  """
  Globally unique identifier for a record to support Global Object Identification.
  Uses format `jl:<key>` where `key` is `base64(json({ 1: journalId }))`.
  """
  id: ID!

  "Unique identifier for the journal."
  journalId: UUID!

  "Name for the journal."
  name: String!

  "Description of the journal."
  description: String!

  "Operational status of the journal. `ACTIVE` journals can be written to with `postTransaction`, whereas `LOCKED` journals do not allow transactions to be posted to them."
  status: Status!

  "Optional unique code for the journal. The default journal uses the code `DEFAULT`."
  code: String

  """
  Journal specific configuration options for transactions and balances
  recorded in this journal.
  """
  config: JournalConfig!

  "Date and time when the journal was first created."
  created: Timestamp!

  "Time of the last change. Especially useful when reviewing the `history`."
  modified: Timestamp!

  "The current version number of this journal. Previous versions are tracked in `history`."
  version: Int!

  _recordId: UUID!

  """
  History of changes to this Journal record.
  Because ledgers are immutable and append-only, all changes are recorded as sequenced versions of the record, providing an unbroken lineage of the current state.
  """
  history(
    "Number of nodes to return on the connection."
    first: Int!
    "Cursor indicating the start point to retrieve nodes. When no cursor is provided, the query uses the default starting cursor."
    after: String
  ): JournalConnection! @goField(forceResolver: true)
}

"System configuration for a journal."
type JournalConfig {
  """
  When `true`, records point-in-time effective balances for all accounts in the journal.
  Defaults to `false`.
  """
  enableEffectiveBalances: Boolean!
}

"""
Connection to a list of Journal nodes.
Access Journal nodes directly through the `nodes` field, or access information about the connection edges with the `edges` field.
Use `pageInfo` to paginate responses using the cursors provided.
"""
type JournalConnection implements Connection {
  nodes: [Journal]!
  edges: [JournalConnectionEdge]!
  pageInfo: PageInfo!
}

"""
Edges represent links connecting a parent or query field to a list of Journal nodes.
They contain a reference to the Journal node and metadata like the `cursor` position for the edge.
"""
type JournalConnectionEdge {
  "Cursor position at this edge."
  cursor: String!
  "Reference to the Journal node at this edge."
  node: Journal
}

"Specify the pre-defined JournalIndex and sort order to use in a query."
input JournalIndexInput {
  name: JournalIndex!
  sort: SortOrder
}

"Indexes for querying Journals. To optimize query performance and apply desired filters, choose the appropriate index."
enum JournalIndex {
  "Index by `JOURNAL_ID` field. Must supply a `journalId: { eq: <id> }` filter to the `where` object."
  JOURNAL_ID
  "Index by `name` field. Use to apply query filters on the value of `name`."
  NAME
  "Index by `status` field. Use to apply query filters on the value of `status`."
  STATUS
  "Index by `code` field. Use to apply query filters on the value of `code`."
  CODE
}

"""
Filter conditions to apply to a journal query.
Filters are only applied if the field is used by the specified index.
"""
input JournalFilterInput {
  "Filter on the `journalId` field. Required when using index `JournalIndex.JOURNAL_ID`."
  journalId: FilterValue
  "Filter on the `name` field. Only available when using index `JournalIndex.NAME`."
  name: FilterValue
  "Filter on the `status` field. Only available when using index `JournalIndex.STATUS`."
  status: FilterValue
  "Filter on the `code` field. Only available when using index `JournalIndex.CODE`."
  code: FilterValue
}

"Fields to create a system configuration for a journal."
input JournalConfigInput {
  """
  When `true`, records point-in-time effective balances for all accounts in the journal.
  Defaults to `false`.
  """
  enableEffectiveBalances: Boolean
}

"Fields to create a new Journal."
input JournalInput {
  "Unique identifier for the journal."
  journalId: UUID!
  "Name for the journal."
  name: String!
  "Description of the journal."
  description: String
  "Operational status of the journal."
  status: Status! = ACTIVE
  "Optional unique code for the journal."
  code: String
  "System config for the journal."
  config: JournalConfigInput
}

"Journal fields to update."
input JournalUpdateInput {
  "Name for the journal."
  name: String
  "Description of the journal."
  description: String
  "Operational status of the journal."
  status: Status
  "The code used to refer to this journal."
  code: String
}
