extend type Query {
  "Get a single tran code by its `tranCodeId`."
  tranCode("Unique identifier." id: UUID!): TranCode

  "Select one or more tran codes. Specify the index to use and apply filters to your query."
  tranCodes(
    """
    Select from a list of pre-defined indexes. For optimal performance, choose specific indexes on unique fields over more general ones.
    """
    index: TranCodeIndexInput!
    """
    Filter the query according to specified conditions. Depending on the index chosen, different filters will be allowed.
    """
    where: TranCodeFilterInput
    "Number of nodes to return on the connection."
    first: Int!
    "Cursor indicating the start point to retrieve nodes. When no cursor is provided, the query uses the default starting cursor."
    after: String
  ): TranCodeConnection!
}

extend type Mutation {
  "Create a new transaction code (tran code)."
  createTranCode(input: TranCodeInput!): TranCode!

  "Update an existing tran code. To ensure data integrity, only a subset of fields are allowed."
  updateTranCode("Unique identifier." id: UUID!, input: TranCodeUpdateInput!): TranCode!

  "Moves the tran code into `LOCKED` status. Prevents transactions from posting using this version of tran code."
  deleteTranCode("Unique identifier." id: UUID!): TranCode
}

"""
Transaction Codes (tran codes) are how financial engineers do double-entry accounting. They encode the basic patterns for a type of transaction as a predictable and repeatable formula.

You can think of tran codes as function signatures which define how a transaction acts upon the ledger.
"""
type TranCode implements Node {
  """
  Globally unique identifier for a record to support Global Object Identification.
  Uses format `tc:<key>` where `key` is `base64(json({ 1: tranCodeId }))`.
  """
  id: ID!

  "Internal UUID for the transaction code record."
  tranCodeId: UUID!

  """
  The tran code represented as a unique string identifier.

  The code itself is a shorthand for the behavior represented. For example, the code `ACH_CREDIT` may represent a transaction writing two entries: an `ACH_DR` entry and an `ACH_CR` entry.
  """
  code: String!

  "Explanation of what this tran code represents and how it should be used. This provides documentation for the tran code."
  description: String!

  "Defines the parameters that can be used when posting transactions using this tran code."
  params: [ParamDefinition]

  "Definition of the transaction posted when this tran code is invoked."
  transaction: TranCodeTransaction!

  "Definition of the entries written when transactions are posted with this tran code."
  entries: [TranCodeEntry!]!

  # TODO: add LOCKED status with message "To avoid rewriting accounting history, tran codes should never be deleted but simply marked 'LOCKED'."
  "Operational status of the tran code."
  status: Status!

  "Metadata attached to this tran code."
  metadata: JSON

  """
  CEL expressions that are evaluated before transaction and entries and can be used a scratch pad area.
  """
  vars: ExpressionNestedMap

  "Date and time when the tran code was first created."
  created: Timestamp!

  "Time of the last change. Especially useful when reviewing the `history`."
  modified: Timestamp!

  "The current version number of this account. Previous versions are tracked in `history`."
  version: Int!

  _recordId: UUID!

  """
  History of changes to this TranCode record.
  Because ledgers are immutable and append-only, all changes are recorded as sequenced versions of the record, providing an unbroken lineage of the current state.
  """
  history(
    "Number of nodes to return on the connection."
    first: Int!
    "Cursor indicating the start point to retrieve nodes. When no cursor is provided, the query uses the default starting cursor."
    after: String
  ): TranCodeConnection! @goField(forceResolver: true)
}

"""
Definition of a parameter that can be used when posting transactions using this tran code.

These definitions are used to validate the provided `params` in a TransactionInput to ensure that only the right data is applied to the entries created.

With CEL, you can access the post-time values of these parameters inside of values in `transaction` and `entries`.
"""
type ParamDefinition {
  """
  Name for the parameter.
  This is how values passed are accessed. For example, a parameter with name `fromAccount` can be accessed in the `accountId` field of an TranCodeEntryInput with `params.fromAccount`.
  """
  name: String!
  "Data type for the parameter."
  type: ParamDataType!
  """
  Default value for the parameter.
  If not provided, the parameter is consider a 'required' parameter, and a value must be provided when posting a transaction.
  """
  default: Expression
  "Describe the purpose of this parameter. Help an engineer out."
  description: String
}

"Definition of the transaction posted when this tran code is invoked."
type TranCodeTransaction {
  "Effective date for transactions posted with this tran code."
  effective: Expression!

  "Journal ID for transactions posted with this tran code."
  journalId: Expression!

  "Correlation ID for transactions posted with this tran code."
  correlationId: Expression

  "External ID for transactions posted with this tran code."
  externalId: Expression

  "Description for transactions posted with this tran code."
  description: Expression!

  "Metadata for transactions posted with this tran code."
  metadata: Expression!
}

"Definition of an entry written when transactions are posted with this tran code."
type TranCodeEntry {
  "Entry type for an entry written when this tran code is invoked."
  entryType: Expression!

  "Account ID for an entry written when this tran code is invoked."
  accountId: Expression!

  "Layer for an entry written when this tran code is invoked."
  layer: Expression!

  "Direction for an entry written when this tran code is invoked."
  direction: Expression!

  "Units of currency for an entry written when this tran code is invoked."
  units: Expression!

  "Currency used for an entry written when this tran code is invoked."
  currency: Expression!

  "Description for an entry written when this tran code is invoked."
  description: Expression

  "Metadata for entries posted with this tran code."
  metadata: Expression

  """
  A boolean expression that indicates if this entry should be written.
  @example("params.amount > decimal(0.00)")
  """
  condition: Expression
}

"""
Connection to a list of TranCode nodes.
Access TranCode nodes directly through the `nodes` field, or access information about the connection edges with the `edges` field.
Use `pageInfo` to paginate responses using the cursors provided.
"""
type TranCodeConnection implements Connection {
  nodes: [TranCode]!
  edges: [TranCodeConnectionEdge]!
  pageInfo: PageInfo!
}

"""
Edges represent links connecting a parent or query field to a list of TranCode nodes.
They contain a reference to the TranCode node and metadata like the `cursor` position for the edge.
"""
type TranCodeConnectionEdge {
  "Cursor position at this edge."
  cursor: String!
  "Reference to the TranCode node at this edge."
  node: TranCode
}

"Specify the pre-defined TranCodeIndex and sort order to use in a query."
input TranCodeIndexInput {
  name: TranCodeIndex!
  sort: SortOrder
}

"Indexes for querying TranCodes. To optimize query performance and apply desired filters, choose the appropriate index."
enum TranCodeIndex {
  "Index by `tranCodeId` field. Must supply a `tranCodeId: { eq: <id> }` filter to the `where` object."
  TRAN_CODE_ID
  "Index by `code` field. Use to apply query filters on the value of `code`."
  CODE
  "Index by `status` field. Use to apply query filters on the value of `status`."
  STATUS
  "Use a custom-defined index. Must supply a `custom` filter to the `where` object."
  CUSTOM
  "Use eventually consisent search. Must supply a `search` filter to the `where` object."
  SEARCH
}

"""
Filter conditions to apply to a tran code query.
Filters are only applied if the field is used by the specified index.
"""
input TranCodeFilterInput {
  "Filter on the `tranCodeId` field. Required when using index `TranCodeIndex.TRAN_CODE_ID`."
  tranCodeId: FilterValue
  "Filter on the `code` field. Only available when using index `TranCodeIndex.CODE`."
  code: FilterValue
  "Filter on the `status` field. Only available when using index `TranCodeIndex.STATUS`."
  status: FilterValue
  "Filter conditions for a custom index. Only available when using index `TranCodeIndex.CUSTOM`."
  custom: CustomIndexFilter
  "Filter conditions for a search.  Only available when using index `TranCodeIndex.SEARCH`."
  search: SearchFilter
}

"Fields to create a new TranCode."
input TranCodeInput {
  "Internal UUID for the transaction code record."
  tranCodeId: UUID!
  "The tran code represented as a unique string identifier. @example('ACH_CREDIT')"
  code: String!
  "Explanation of what this tran code represents and how it should be used. This provides documentation for the tran code."
  description: String
  "Define the parameters that can be used when posting transactions using this tran code."
  params: [ParamDefinitionInput!]
  "Define the values for the transaction posted when this tran code is invoked."
  transaction: TranCodeTransactionInput!
  "Define the values of entries written when transactions are posted with this tran code."
  entries: [TranCodeEntryInput!]!
  "Metadata attached to this tran code."
  metadata: JSON
  "Calculation area evaluated and injected as `vars` for transaction and entry evaluation."
  vars: ExpressionNestedMap
}

"""
Define a parameter that can be used when posting transactions using this tran code.
"""
input ParamDefinitionInput {
  """
  Name for the parameter.
  This is how values passed are accessed. For example, a parameter with name `fromAccount` can be accessed in the `accountId` field of an TranCodeEntryInput with `params.fromAccount`.
  """
  name: String!
  "Data type for the parameter."
  type: ParamDataType! = STRING
  """
  Default value for the parameter.
  If not provided, the parameter is consider a 'required' parameter, and a value must be provided when posting a transaction.
  """
  default: Expression
  "Describe the purpose of this parameter. Help an engineer out."
  description: String
}

"Define the values for the transaction posted when this tran code is invoked."
input TranCodeTransactionInput {
  """
  Effective date for the transaction posted with this tran code.
  If ommitted, defaults to `date.Today()`.
  Expression must be a valid ISO 8601 formatted date.
  @example("date('2022-12-23')")
  """
  effective: Expression

  """
  Journal ID for the transaction posted with this tran code.
  If omitted, the default journal will be used.
  Expression must resolve to a UUID type.
  @example("uuid('b28f5684-0834-4292-8016-d2f2fb0367a9')")
  """
  journalId: Expression

  """
  Correlation ID for the transaction posted with this tran code.
  Expression must resolve to a String type.
  @example("'5a028997'")
  """
  correlationId: Expression

  """
  External ID for the transaction posted with this tran code.
  Expression must resolve to a String type.
  @example("'45415819'")
  """
  externalId: Expression

  """
  Description for the transaction posted with this tran code.
  Expression must resolve to a String type.
  @example("'TX for ' + string(params.amount)")
  """
  description: Expression

  """
  Metadata for the transaction posted with this tran code.
  Expression must resolve to a JSON type.
  @example("{ 'x': 1, 'y': { 'z': 2 }}")
  """
  metadata: Expression
}

"Defines the values for the entries written when transactions are posted with this tran code."
input TranCodeEntryInput {
  """
  Account ID for an entry written when this tran code is invoked.
  Expression must resolve to a UUID type.
  """
  accountId: Expression!

  """
  Units of currency for an entry written when this tran code is invoked.
  Expression must resolve to a Decimal type.
  """
  units: Expression!

  """
  Currency used for an entry written when this tran code is invoked.
  Expression must resolve to a CurrencyCode type.
  """
  currency: Expression!

  """
  Direction for an entry written when this tran code is invoked.
  Expression must resolve to a DebitOrCredit enum type.
  """
  direction: Expression!

  """
  Entry type for an entry written when this tran code is invoked.
  If omitted, defaults to `tranCode.code` with `_CR` or `_DR` appended depending on entry `direction`.
  Expression must resolve to a String type.
  """
  entryType: Expression

  """
  Layer for an entry written when this tran code is invoked.
  If omitted, defaults to `SETTLED` layer.
  Expression must resolve to a Layer enum type.
  """
  layer: Expression

  """
  Description for an entry written when this tran code is invoked."
  Expression must resolve to a String type.
  """
  description: Expression

  """
  Metadata for the entry posted with this tran code.
  Expression must resolve to a JSON type.
  @example("{ 'x': 1, 'y': { 'z': 2 }}")
  """
  metadata: Expression

  """
  A boolean expression that indicates if this entry should be written.
  @example("params.amount > 0")
  """
  condition: Expression
}

"TranCode fields to update."
input TranCodeUpdateInput {
  "Explanation of what this tran code represents and how it should be used. This provides documentation for the tran code."
  description: String
  """
  Define the parameters that can be used when posting transactions using this tran code.
  Replaces existing parameters definition.
  """
  params: [ParamDefinitionInput!]
  """
  Define values for transaction posted when this tran code is invoked.
  Replaces existing transaction definition.
  """
  transaction: TranCodeTransactionInput
  """
  Define the values of entries written when transactions are posted with this tran code.
  Replaces existing entry definition.
  """
  entries: [TranCodeEntryInput!]
  "Operational status of the tran code."
  status: Status
  "Metadata attached to this tran code."
  metadata: JSON
  "Variables for computation."
  vars: ExpressionNestedMap
}
