extend type Query {
  "Get a single transaction by its `transactionId`."
  transaction("Unique identifier." id: UUID!): Transaction

  "Select one or more transactions. Specify the index to use and apply filters to your query."
  transactions(
    """
    Select from a list of pre-defined indexes. For optimal performance, choose specific indexes on unique fields over more general ones.
    """
    index: TransactionIndexInput!
    """
    Filter the query according to specified conditions. Depending on the index chosen, different filters will be allowed.
    """
    where: TransactionFilterInput
    "Number of nodes to return on the connection."
    first: Int!
    "Cursor indicating the start point to retrieve nodes. When no cursor is provided, the query uses the default starting cursor."
    after: String
  ): TransactionConnection!
}

extend type Mutation {
  "Write a transaction to the ledger using the predefined defaults from the `tranCode` provided."
  postTransaction(input: TransactionInput!): Transaction!

  "Update an existing transaction. To ensure data integrity, only a subset of fields are allowed."
  updateTransaction("Unique identifier." id: UUID!, input: TransactionUpdateInput!): Transaction!

  "Void an existing transaction."
  voidTransaction("Unique identifier." id: UUID!): Transaction!
}

"""
Transactions record all accounting events in the ledger. In Twisp, the only way to write to a ledger is through a transaction.

Every transaction writes two or more entries to the ledger in standard double-entry accounting practice.

Twisp expands upon the basic principle of an accounting transaction with additional features like transaction codes and correlations.
"""
type Transaction implements Node {
  """
  Globally unique identifier for a record to support Global Object Identification.
  Uses format `tx:<key>` where `key` is `base64(json({ 1: transactionId }))`.
  """
  id: ID!
  "Unique identifier for the transaction."
  transactionId: UUID!

  "Unique identifier for the tran code used by this transaction."
  tranCodeId: UUID!

  "Unique identifier for the journal this transaction applies to."
  journalId: UUID!

  """
  Allows related transactions to be grouped.

  When a transaction is posted without a `correlationId`, it uses the `transactionId` as the `correlationId`. Then, future related transactions can be posted with the same `correlationId` to indicate their relationship to the original. This is very useful for events like holds, auths, auth reversals, etc.

  For example, consider the following (simplified) list of transactions:

  (ID: 1) Place card hold for $50 on account A (correlation ID: 1)
  (ID: 2) Place card hold for $20 on account B (correlation ID: 2)
  (ID: 3) Release card hold for $50 on account A (correlation ID: 1)

  Because transaction (3) is _related_ to transaction (1), it shares the same correlation ID. This way, we can easily observe the entire history of a multi-transaction event by querying the correlated transactions.
  """
  correlationId: String!

  "Allows specifying a unique external ID associated with this transaction."
  externalId: String!

  "The effective date records when the transaction is recorded as occurring for accounting purposes. Determines the accounting period within which the transaction is counted."
  effective: Date!

  "Description of the transaction."
  description: String!

  "Arbitrary structured data about this transaction."
  metadata: JSON

  "The voided by records the transaction identifier that voided this transaction."
  voidedBy: UUID

  "The void of records the transaction identifier this transaction is voiding"
  voidOf: UUID

  "Date and time when the transaction was first posted."
  created: Timestamp!

  "Time of the last change. Especially useful when reviewing the `history`."
  modified: Timestamp!

  properties: TransactionProperties!

  "The current version number of this transaction. Previous versions are tracked in `history`."
  version: Int!

  _recordId: UUID!

  "List of all correlated transactions. These are transactions which share the same `correlationId`."
  correlated(
    "Number of nodes to return on the connection."
    first: Int!
    "Cursor indicating the start point to retrieve nodes. When no cursor is provided, the query uses the default starting cursor."
    after: String
  ): TransactionConnection! @goField(forceResolver: true)

  "Ledger entries written by the transaction."
  entries(
    "Number of nodes to return on the connection."
    first: Int!
    "Cursor indicating the start point to retrieve nodes. When no cursor is provided, the query uses the default starting cursor."
    after: String
  ): EntryConnection! @goField(forceResolver: true)

  """
  History of changes to this Transaction record.
  Because ledgers are immutable and append-only, all changes are recorded as sequenced versions of the record, providing an unbroken lineage of the current state.
  """
  history(
    "Number of nodes to return on the connection."
    first: Int!
    "Cursor indicating the start point to retrieve nodes. When no cursor is provided, the query uses the default starting cursor."
    after: String
  ): TransactionConnection! @goField(forceResolver: true)

  "Reference to the journal this transaction applies to."
  journal: Journal! @goField(forceResolver: true)

  "Reference to the tran code used by this transaction."
  tranCode: TranCode! @goField(forceResolver: true)

  "Reference to any exceptions, if occurred."
  exceptions: [TransactionException!] @goField(forceResolver: true)

  "Look up the workflow executions that produced this transaction."
  workflows(
    "Return workflow executions for all versions of this transaction"
    all: Boolean = false
    "Number of nodes to return on the connection."
    first: Int!
    "Cursor indicating the start point to retrieve nodes. When no cursor is provided, the query uses the default starting cursor."
    after: String
  ): WorkflowExecutionConnection @goField(forceResolver: true)
}

type TransactionProperties {
  """
  Overrides velocity enforcements that have an action of `VOID` or `REJECT`.
  Useful for forced postings that require disabled velocity control enforcement (e.g. set to `WARN`).
  """
  overrideVelocityEnforcement: VelocityEnforcement
}

type TransactionException {
  type: String!
  message: String!
  detail: JSON!
}

"""
Connection to a list of Transaction nodes.
Access Transaction nodes directly through the `nodes` field, or access information about the connection edges with the `edges` field.
Use `pageInfo` to paginate responses using the cursors provided.
"""
type TransactionConnection implements Connection {
  nodes: [Transaction]!
  edges: [TransactionConnectionEdge]!
  pageInfo: PageInfo!
}

"""
Edges represent links connecting a parent or query field to a list of Transaction nodes.
They contain a reference to the Transaction node and metadata like the `cursor` position for the edge.
"""
type TransactionConnectionEdge {
  "Cursor position at this edge."
  cursor: String!
  "Reference to the Transaction node at this edge."
  node: Transaction
}

"Specify the pre-defined TransactionIndex and sort order to use in a query."
input TransactionIndexInput {
  name: TransactionIndex!
  sort: SortOrder
}

"Indexes for querying Transactions. To optimize query performance and apply desired filters, choose the appropriate index."
enum TransactionIndex {
  "Index by `TRANSACTION_ID` field. Must supply a `transactionId: { eq: <id> }` filter to the `where` object."
  TRANSACTION_ID
  "Index by `CORRELATION_ID` field. Must supply a `correlationId: { eq: <id> }` filter to the `where` object."
  CORRELATION_ID
  "Index by `EXTERNAL_ID` field. Must supply an `externalId: { eq: <id> }` filter to the `where` object."
  EXTERNAL_ID
  "Use a custom-defined index. Must supply a `custom` filter to the `where` object."
  CUSTOM
  "Use eventually consisent search. Must supply a `search` filter to the `where` object."
  SEARCH
  "Retrieve a list of transactions by id. Must supply an `ids` filter to the `where` object."
  TRANSACTION_IDS
  "Retrieve a list of transactions by group. Must supply a `group` filter to the `where` object."
  GROUP
}

"""
Filter conditions to apply to a transaction query.
Filters are only applied if the field is used by the specified index.
"""
input TransactionFilterInput {
  "Specify the Journal to use with `eq`. If omitted, the default journal will be used."
  journalId: FilterValue
  "Filter on the `transactionId` field. Required when using index `TransactionIndex.TRANSACTION_ID`."
  transactionId: FilterValue
  "Filter on the `correlationId` field. Required when using index `TransactionIndex.CORRELATION_ID`."
  correlationId: FilterValue
  "Filter on the `externalId` field. Required when using index `TransactionIndex.EXTERNAL_ID`."
  externalId: FilterValue
  "Filter on the `group` field. Required when using index `TransactionIndex.GROUP`."
  group: FilterValue
  "Filter conditions for a custom index. Only available when using index `TransactionIndex.CUSTOM`."
  custom: CustomIndexFilter
  "Filter conditions for a search.  Only available when using index `TransactionIndex.SEARCH`."
  search: SearchFilter
  "Retrieve up to 100 transactions by id."
  transactionIds: [UUID!]
}

"Fields to post a new Transaction."
input TransactionInput {
  "The ID is required to ensure an idempotent transaction."
  transactionId: UUID!
  "String corresponding to the `code` of a TranCode to be used for this transaction."
  tranCode: String!
  """
  Version of the tran code to use in this transaction.
  If not supplied, the latest version will be used.
  """
  tranCodeVersion: Int
  "Params object specifying values for the params defined in the corresponding TranCode."
  params: JSON
  """
  Set various transaction properties, including changing velocity enforcement.
  """
  properties: TransactionPropertiesInput
}

input TransactionPropertiesInput {
  """
  Override velocity enforcement for this request. If a velocity control action will enforce at
  `VOID` or `REJECT`, will enforce with the action specified in this request.

  This is useful for force posts, where you want to disable a velocity control with an action of `WARN`.
  """
  overrideVelocityEnforcement: VelocityEnforcementInput

  """
  If provided, will post transaction and immediately void. Will also create the transaction
  exception provided that is returned on `Transaction.exceptions`.  Using this option will
  automatically set the `overrideVelocityEnforcement.action` to `WARN`, allowing all
  velocity controls to evaluate and write exceptions at WARN level.
  """
  exception: TransactionExceptionInput
}

input TransactionExceptionInput {
  """
  Human readable code that describes the type of exception.

  @example("FRAUD")
  """
  type: String!

  """
  Human readable message that gives contextual detail about why this exception has occurred.

  @example("fraud system indicated 95% chance of fraud")
  """
  message: String!
  """
  Arbitrary structured data about this particular exception.
  """
  detail: JSON!
}

"Transaction fields to update."
input TransactionUpdateInput {
  "Allows specifying a unique external ID associated with this transaction."
  externalId: String
  "Description of the transaction."
  description: String
  "Arbitrary structured data about this transaction."
  metadata: JSON
}
