extend type Query {
  # Apply a set of rules to an account or set.
  velocityControl(id: UUID!): VelocityControl
  velocityControls(
    index: VelocityControlIndexInput!
    where: VelocityControlFilterInput
    first: Int! = 100
    after: String
  ): VelocityControlConnection

  # Velocity Limits.
  velocityLimit(id: UUID!): VelocityLimit
  velocityLimits(
    index: VelocityLimitIndexInput!
    where: VelocityLimitFilterInput
    first: Int! = 100
    after: String
  ): VelocityLimitConnection

  """
  Search for the velocity balance for an Account or Account Set.
  """
  velocity(
    "Account or Account Set to search for velocity."
    accountId: UUID!
    """
    The window of the balance to look up. If
    `velocityLimitId` not provided, will look up
    all velocity limits that support the defined
    window.
    @example({year: "2022", month:"9"})
    """
    window: JSON!
    "The currency for the velocity to look up."
    currency: CurrencyCode! = "USD"
    "If provided, retrieve this specific velocity limit."
    velocityLimitId: UUID
    "If provided, retrieve from specified journal. Otherwise will use default."
    journalId: UUID
  ): [VelocityBalance]

  """
  List all velocity controls attached the specified Account or Account Set.
  """
  attachedControls(
    "Account or Account Set Id to look up attached controls"
    accountId: UUID!
    first: Int!
    after: String! = ""
  ): ResolvedVelocityControlConnection! @goField(forceResolver: true)
}

extend type Mutation {
  createVelocityControl(input: VelocityControlInput!): VelocityControl!
  updateVelocityControl(
    velocityControlId: UUID!
    input: UpdateVelocityControlInput!
  ): VelocityControl
  deleteVelocityControl(velocityControlId: UUID!): VelocityControl

  createVelocityLimit(input: VelocityLimitInput!): VelocityLimit!
  updateVelocityLimit(velocityLimitId: UUID!, input: UpdateVelocityLimitInput!): VelocityLimit
  deleteVelocityLimit(velocityLimitId: UUID!): VelocityLimit

  """
  Attach an account or set to the control.
  """
  attachVelocityControl(
    "The control to attach account limit to."
    velocityControlId: UUID!
    """
    Account or Set Id to attach to the velocity control to.
    """
    accountId: UUID!
    """
    Journal on which journal to attach the velocity control to.
    Attaches to the default journal if not provided.
    """
    journalId: UUID
    """
    The parameters for the velocity limit to use.
    If attaching for default limits for control (`velocityLimitId == null`),
    Then params must satify all defined params on defualt limits
    """
    params: JSON
  ): VelocityControl

  """
  detach account from control.
  """
  detachVelocityControl(
    "The Velocity Control to detach."
    velocityControlId: UUID!
    "The account id detaching from."
    accountId: UUID!
    """
    The journal detaching from. If not provided this will detach from default journal.
    """
    journalId: UUID
  ): VelocityControl

  """
  Add a limit to the control.
  """
  addLimitToControl(
    "The control to add limit to."
    velocityControlId: UUID!
    "The velocity limit to add."
    velocityLimitId: UUID!
  ): VelocityControl

  """
  Remove a single limit from control.
  """
  removeLimitFromControl(
    "The control to remove from."
    velocityControlId: UUID!
    "The velocity limit to remove."
    velocityLimitId: UUID!
  ): VelocityControl

  """
  Remove all limits from the velocity control.
  """
  removeAllLimitsFromControl(
    "The control to remove from."
    velocityControlId: UUID!
  ): VelocityControl
}

enum VelocityControlIndex {
  "Index by `velocityControlId` field. Must supply an `velocityControlId: { eq: <id> }` filter to the `where` object."
  VELOCITY_CONTROL_ID
  "Index by `name` field. Use to apply query filters on the value of `name`."
  NAME
  "Index by `accountId` attached to velocity control. Must supply an `accountId: { eq: <id> }` filter to the `where` object."
  ACCOUNT_ID

  VELOCITY_LIMIT_ID
}

input VelocityControlIndexInput {
  name: VelocityControlIndex!
  sort: SortOrder
}

input VelocityControlFilterInput {
  "Filter on the `velocityControlId` field. Required when using index `VelocityControlIndex.VELOCITY_CONTROL_ID`."
  velocityControlId: FilterValue
  "Filter on the `velocityLimitId` field. Required when using index `VelocityControlIndex.VELOCITY_RULE_ID`."
  velocityLimitId: FilterValue
  "Filter on the `name` field. Required when using index `VelocityControlIndex.NAME`."
  name: FilterValue
  "Filter on attached accounts via `accountId`. Required when using index `VelocityControlIndex.ACCOUNT_ID`."
  accountId: FilterValue
}

enum VelocityLimitIndex {
  "Index by `velocityLimitId` field. Must supply an `velocityLimitId: { eq: <id> }` filter to the `where` object."
  VELOCITY_LIMIT_ID
  "Index by `name` field. Use to apply query filters on the value of `name`."
  NAME
}

input VelocityLimitIndexInput {
  name: VelocityLimitIndex!
  sort: SortOrder
}

input VelocityLimitFilterInput {
  "Filter on the `velocityLimitId` field. Required when using index `VelocityLimitIndex.VELOCITY_RULE_ID`."
  velocityLimitId: FilterValue
  "Filter on the `name` field. Required when using index `VelocityLimitIndex.NAME`."
  name: FilterValue
}

type VelocityControlConnection implements Connection {
  nodes: [VelocityControl]!
  edges: [VelocityControlConnectionEdge]!
  pageInfo: PageInfo!
}

type VelocityControlConnectionEdge {
  cursor: String!
  node: VelocityControl
}

type VelocityLimitConnection implements Connection {
  nodes: [VelocityLimit]!
  edges: [VelocityLimitConnectionEdge]!
  pageInfo: PageInfo!
}

type VelocityLimitConnectionEdge {
  cursor: String!
  node: VelocityLimit
}

type VelocityControl implements Node {
  id: ID!
  "Unique identifier of this control."
  velocityControlId: UUID!
  "Human readable name of this control."
  name: String!
  "Human readable description of this control."
  description: String!
  "The the enforcement this control produces."
  enforcement: VelocityEnforcement!
  """
  A boolean expression indicating if control should enforce.
  The `account`, `transaction`, `balance` and `entry` are available for use in the dimension computation on `context.vars`.
  @example("has(context.vars.account.metadata.policyPayment)")
  """
  condition: Expression

  "Set of default velocity limits for this control."
  limits: [VelocityLimit]! @goField(forceResolver: true)
}

type VelocityLimit implements Node {
  id: ID!
  "Unique identifier for this velocity limit."
  velocityLimitId: UUID!

  """
  Human readable name of this limit.
  """
  name: String!

  """
  "
  Human readable description of this limit.
  """
  description: String!

  """
  Group by these values to index the calculation.

  The `account`, `transaction`, `tranCode` and `entry` are available for use in the dimension computation on `context.vars`.
  """
  window: [PartitionKey]!

  """
  A boolean expression indicating if an balance entry should be written.
  The `account`, `transaction` and `entry` are available for use in the dimension computation on `context.vars`.
  @example("has(context.vars.account.metadata.policyPayment)")
  """
  condition: Expression

  """
  The limit to enforce.
  """
  limit: Limit!

  """
  The currency this limit  applies to. If an empty string, applies to all limits.
  """
  currency: CurrencyCode!

  """
  Parameters for `VelocityLimit.limit`
  """
  params: [ParamDefinition]
}

input VelocityControlInput {
  "Unique identifier for this velocity control."
  velocityControlId: UUID!
  "Human readable name for this velocity control."
  name: String!
  "Human readable description for this velocity control."
  description: String!
  "The type of enforcement this velocity control generates."
  enforcement: VelocityEnforcementInput!
  """
  A boolean expression indicating if this control should trigger enforcement.
  The `account`, `transaction` and `entry` are available for use on `context.vars`.
  @example("context.vars.transaction.?metadata.skipVelocityControl.orElse(false))")
  """
  condition: Expression

  """
  Add these velocity limits to the control.
  """
  velocityLimitIds: [UUID!]
}

input VelocityLimitInput {
  velocityLimitId: UUID!

  """
  Human readable name of this rule.
  """
  name: String!

  """
  "
  Human readable description of this rule.
  """
  description: String!

  """
  Group by these values to index the calculation.

  The `account`, `transaction`, `tranCode` and `entry` are available for use in the window computation on `context.vars`.
  """
  window: [PartitionKeyInput]!

  """
  A boolean expression indicating if an balance entry should be written.
  The `account`, `transaction` and `entry` are available for use in the window computation on `context.vars`.
  @example("has(context.vars.account.metadata.policyPayment)")
  """
  condition: Expression

  """
  The limit to enforce. Can supply different limits based
  """
  limit: LimitInput!

  """
  Currency this limit applies to. If set to empty string, applies limit to all currencies.
  """
  currency: CurrencyCode!

  """
  The parameters for `VelocityLimit.limit`.
  """
  params: [ParamDefinitionInput]

  """
  Add the limit to the velocity controls in this list.
  """
  velocityControlIds: [UUID!]
}

type Limit {
  timestampSource: Expression
  balance: [BalanceLimit!]!
}

input LimitInput {
  """
  Uses a timestamp from the specified source for picking the balance limit.
  By default uses the system `transaction.timestamp`.
  Must resolve to a CEL `timestamp`.
  @example("timestamp(context.vars.transaction.?metadata.ts.orValue(context.transaction.timestamp))")
  """
  timestampSource: Expression
  balance: [BalanceLimitInput!]!
}

input UpdateLimitInput {
  """
  Uses timestamp from the specified source for picking the balance limit.
  By default uses the transaction timestamp.
  Must resolve to a CEL `timestamp`.
  @example("timestamp(context.vars.transaction.?metadata.ts.orValue(context.transaction.timestamp))")
  """
  timestampSource: Expression
  balance: [BalanceLimitInput!]
}

input UpdateVelocityControlInput {
  "If set, updates name of velocity control."
  name: String
  "If set, updates description of velocity control."
  description: String
  "If set, updates the enforcement type of the velocity control."
  enforcement: VelocityEnforcementInput
  "If set, updates the condition for the velocity control."
  condition: Expression
}

input UpdateVelocityLimitInput {
  "If set, updates name of velocity limit."
  name: String
  "If set, updates description of velocity limit."
  description: String
  "If set, updates the limit of the velocity limit."
  limit: UpdateLimitInput
  "If set, sets the currency of the velocity limit. Cannot unset."
  currency: CurrencyCode
  "If Set, sets the condition of the velocity limit."
  condition: Expression
}

enum VelocityEnforcementAction {
  "Returns a selectable exception on postTransaction.exceptions, but allows transaction to be posted."
  WARN
  "Returns a selectable exception on postTransaction.exceptions, and voids offending transaction."
  VOID
  "Returns an exception as an error, aborting entire request."
  REJECT
}

input VelocityEnforcementInput {
  action: VelocityEnforcementAction!
}

type VelocityEnforcement {
  action: VelocityEnforcementAction!
}

enum BalanceLimitType {
  "Limit based on available balance at a particular layer."
  AVAILABLE
}

input BalanceLimitInput {
  """
  The layer this balance limit is enforced at.
  Must resolve to `SETTLED`, `PENDING` or `ENCUMBRANCE`.
  """
  layer: Expression!
  """
  The maximum amount at this layer that can be spent. Must resolve to a decimal.
  """
  amount: Expression!
  """
  The direction this balance enforces on as an upper limit.
  Must resolve to `CREDIT` or `DEBIT`.
  """
  normalBalanceType: Expression!
  """
  The timestamp at which this balance limit begins to be effective.
  If provided, must resolve to a `timestamp`.
  Defaults to the creation stamp of the underlying control.
  @example("timestamp('2022-01-01T14:00:00.000Z')")
  """
  start: Expression
  """
  The timestamp at which this balance limit ceases to be effective.
  If provided, must resolve to a `timestamp`.
  Defaults to infinite timestamp.
  @example("timestamp('2022-01-01T15:00:00.000Z')")
  """
  end: Expression
}

type BalanceLimit {
  "The layer this balance limit is enforced at."
  layer: Expression!
  "The maximum amount at this layer that can be spent."
  amount: Expression!
  "The direction this balance enforces on."
  NormalBalanceType: Expression!
  "The timestamp at which this balance limit begins to be effective."
  start: Expression
  "The timestamp at which this balance limit ceases to be effective."
  end: Expression
}

input VelocityWindowInput {
  "The account or set id to search for velocity."
  accountId: UUID!
  "Limit the search to this velocity control Id."
  velocityControlId: UUID!
  "Limit the search to this velocity limit."
  velocityLimitId: UUID
  """
  The window to search. If `velocityLimitId` not present,
  will return any limit that supports the _entire_ window.
  """
  window: JSON!
  "Return the velocity limit for this currency."
  currency: CurrencyCode! = "USD"
}

type VelocityBalance {
  "The matching velocity control id"
  velocityControlId: UUID!
  "The matching velocity limit."
  velocityLimitId: UUID!
  "The amount spent on the limit."
  spent: Decimal!
  "The amount remaining on the limit."
  remaining: Decimal!
  "The currency of this velocity balance."
  currency: CurrencyCode!
  "Get the velocity limit for this Balance."
  velocityLimit: VelocityLimit!
  "The underlying balance for this velocity."
  balance: Balance!
  "Retrieve the entries in this window."
  entries(first: Int!, after: String): EntryConnection! @goField(forceResolver: true)
}

type ResolvedVelocityControl {
  "Unique identifier of this control."
  velocityControlId: UUID!
  "Journal this velocity control is acting on."
  journalId: UUID!
  "Human readable name of this control"
  name: String!
  "Human readable description of this control."
  description: String!
  "The enforcement this control produces."
  enforcement: VelocityEnforcement!
  """
  A boolean expression indicating if control should enforce control.
  The `account`, `transaction`, `balance` and `entry` are available for use in the dimension computation on `context.vars`.
  @example("has(context.vars.account.metadata.policyPayment)")
  """
  condition: Expression
  "Set of resolved limits for this control."
  limits: [ResolvedVelocityLimit!]!
}

type ResolvedVelocityLimit {
  "Calculation identifier for checking balances on this resolved velocity limit"
  calculationId: UUID!

  "Unique identifier for this velocity limit."
  velocityLimitId: UUID!
  """
  Human readable name of this limit.
  """
  name: String!
  """
  "
  Human readable description of this limit.
  """
  description: String!
  """
  A boolean expression indicating if an balance entry should be written.
  The `account`, `transaction` and `entry` are available for use in the dimension computation on `context.vars`.
  @example("has(context.vars.account.metadata.policyPayment)")
  """
  condition: Expression
  """
  Group by these values to index the calculation.

  The `account`, `transaction`, `tranCode` and `entry` are available for use in the dimension computation on `context.vars`.
  """
  window: [PartitionKey!]!
  """
  The currency this limit  applies to. If an empty string, applies to all limits.
  """
  currency: CurrencyCode!
  """
  Parameters for `VelocityLimit.limit`
  """
  params: [ParamDefinition]
  """
  The resolved values for this velocity limit.
  """
  limit: ResolvedLimit!
}

type ResolvedLimit {
  """
  A resolved balance limit.
  """
  balance: [ResolvedBalanceLimit!]!
}

type ResolvedBalanceLimit {
  """
  Layer at which this balance is balance is enforced.
  """
  layer: Layer!
  """
  Decimal amount of the limit.
  """
  amount: Decimal!
  """
  Normal balance direction of this limit.
  """
  normalBalanceType: DebitOrCredit!
  """
  Timestamp of when this limit starts application.
  """
  start: Timestamp!
  """
  Timestamp of when this limit ends application.
  """
  end: Timestamp!
}

type ResolvedVelocityControlConnection implements Connection {
  nodes: [ResolvedVelocityControl]!
  edges: [ResolvedVelocityControlConnectionEdge]!
  pageInfo: PageInfo!
}

type ResolvedVelocityControlConnectionEdge {
  cursor: String!
  node: ResolvedVelocityControl
}
