extend type Query {
  "Get entries from a specific view by name."
  view(
    "Name of the view to query."
    name: String!
    "Filters to apply based on the view's dimensions."
    where: ViewFilter
    "Number of nodes to return on the connection."
    first: Int!
    "Cursor indicating the start point to retrieve nodes. When no cursor is provided, the query uses the default starting cursor."
    after: String
  ): ViewRecordConnection! @goField(forceResolver: true)
}

"""
Represents a single entry in an view materialized view.
"""
type ViewRecord implements Node {
  """
  Globally unique identifier for this view entry.
  """
  id: ID!

  """
  Name of the view this record is from.
  """
  name: String!

  """
  The document content of this view entry.
  Structure depends on the view definition.
  """
  document: JSON!

  """
  Information about the data source that trigged this version of the document.
  """
  source: ViewTrigger!

  """
  The current version number of this view.
  """
  version: Int!

  _recordId: UUID!

  """
  History of changes to this View record.
  Because ledgers are immutable and append-only, all changes are recorded as sequenced versions of the record, providing an unbroken lineage of the current state.
  """
  history(
    "Number of nodes to return on the connection"
    first: Int!
    "Cursor indicating the start point to retrieve nodes. When no cursor provided, uses default starting cursor"
    after: String
  ): ViewRecordConnection! @goField(forceResolver: true)
}

"""
Connection to a list of ViewEntry nodes.
"""
type ViewRecordConnection implements Connection {
  nodes: [ViewRecord]!
  edges: [ViewRecordConnectionEdge]!
  pageInfo: PageInfo!
}

"""
Edges represent links connecting a parent or query field to a list of ViewEntry nodes.
"""
type ViewRecordConnectionEdge {
  """
  Cursor position at this edge.
  """
  cursor: String!

  """
  Reference to the ViewEntry node at this edge.
  """
  node: ViewRecord
}

type ViewTrigger {
  entity: String!
  trigger: ViewTriggerEnum!
  _oldRecordId: UUID
  _newRecordId: UUID!
  _oldVersion: Int
  _newVersion: Int!

  """
  Resolve the new trigger entity that created this version of the document.
  """
  new: DatabaseEntity! @goField(forceResolver: true)

  """
  Resolve the old trigger entity that created this version of the document.
  """
  old: DatabaseEntity @goField(forceResolver: true)
}
