extend type Mutation {
  "Mutations in the `workflow` namespace are used to manage and execute workflows."
  workflow: WorkflowMutation!
}

extend type Query {
  workflow: WorkflowQuery!
}

type WorkflowQuery {
  """
  Return the execution by execution id.
  """
  execution(executionId: UUID!): WorkflowExecution @goField(forceResolver: true)
}

type WorkflowMutation {
  "Execute a workflow identified by `workflowId`."
  execute(input: WorkflowInput!): WorkflowExecution! @goField(forceResolver: true)

  "Execution workflow identified by `workflowId` and `executionId` to the state identified by `task`."
  executeTask(input: WorkflowInput!): WorkflowExecution! @goField(forceResolver: true)
}

type WorkflowExecution {
  "Workflow Id of workflow invoked."
  workflowId: UUID!
  "Execution Id of this execution."
  executionId: UUID!
  "The task that was invoked on this version of the workflow execution."
  task: String!
  "Parameters supplied for this workflow execution."
  params: JSON
  "Context to pass along to future executions of this workflow."
  context: JSON
  "Output of this invocation of the workflow."
  output: WorkflowExecutionOutput!
  "Errors from this invocation of the workflow."
  error: String

  "Date and time when the execution was first created."
  created: Timestamp!

  "Time of the last change. Especially useful when reviewing the `history`."
  modified: Timestamp!

  "version number of the execution. Previous versions are tracked in history."
  version: Int!
  _recordId: UUID!

  """
  Activities that this workflow took. It may have inserted entities like Transactions or invoked Workflows.
  """
  activities: [WorkflowActivity] @goField(forceResolver: true)

  """
  Workflow execution history for this workflow.
  """
  history(first: Int!, after: String): WorkflowExecutionConnection! @goField(forceResolver: true)

  ## executeTask BC

  """
  Outputs the execution state of the workflow. Depending on the workflow will contain diagnostic detials specific to the workflow.
  """
  state: JSON!
    @goField(forceResolver: true)
    @deprecated(reason: "This is the same as `WorkflowExecution.output.state`.")

  """
  Resolve any posted transactions that this workflow posted in this invocation.
  """
  transactions(first: Int! = 0): [Transaction]
    @goField(forceResolver: true)
    @deprecated(reason: "Use `WorkflowExecution.activities` instead.")
}

type WorkflowActivity {
  action: String!
  entity: WorkflowEntity! @goField(forceResolver: true)
  entityId: UUID!
  entityType: String!
  _recordId: UUID!
  version: Int!

  _workflowId: UUID!
  _executionId: UUID!
  _executionVersion: Int!
}

type WorkflowExecutionConnection implements Connection {
  nodes: [WorkflowExecution]!
  edges: [WorkflowExecutionConnectionEdge]!
  pageInfo: PageInfo!
}

type WorkflowExecutionConnectionEdge {
  cursor: String!
  node: WorkflowExecution
}

type WorkflowExecutionOutput {
  state: JSON
  entities: [WorkflowExecutionOutputEntity]
    @deprecated(reason: "moved to WorkflowExecution.activities")
}

type WorkflowExecutionOutputEntity {
  action: String!
  entity: WorkflowEntity! @goField(forceResolver: true)
  entityId: UUID!
  entityType: String!
  _recordId: UUID!
  version: Int!
}

union WorkflowEntity = Transaction | WorkflowExecution | AchWorkflowTrace

"Fields to execute a new workflow."
input WorkflowInput {
  workflowId: UUID
  executionId: UUID!
  code: String
  task: String!
  params: JSON
}
