query GetTransactions($journalGLId: String!) {
  transactions(
    index: { name: CORRELATION_ID }
    where: {
      correlationId: { eq: "4f2ac9a7-5e83-458b-a194-c8ac8d8fdcd5" }
      journalId: { eq: $journalGLId }
    }
    first: 10
  ) {
    nodes {
      transactionId
      description
      effective
      tranCode {
        code
      }
    }
  }
}
