mutation FundAccounts(
  $bertCheckingId: UUID!
  $ernieCheckingId: UUID!
  $settlementCheckingId: UUID!
) {
  fundBert: postTransaction(
    input: {
      tranCode: "RECORD_TX"
      transactionId: "d52e6593-4973-4522-a065-d6eef9428308"
      params: {
        account: $bertCheckingId
        settlementAccount: $settlementCheckingId
        amount: "100"
        effective: "2022-10-31"
        transactionType: "ACH DEBIT"
        isDebit: "true"
      }
    }
  ) {
    transactionId
  }

  fundErnie: postTransaction(
    input: {
      tranCode: "RECORD_TX"
      transactionId: "cc995feb-fa61-4512-a758-eb7b2c7081a2"
      params: {
        account: $ernieCheckingId
        settlementAccount: $settlementCheckingId
        amount: "500"
        effective: "2022-10-31"
        transactionType: "ACH DEBIT"
        isDebit: "true"
      }
    }
  ) {
    transactionId
  }
}
