query ACHTranCodes {
  achEncumbranceCancelDebit: tranCode(id: "7b24410d-6dbc-44cd-8779-a1bfa827868a") {
    ...TC
  }
  achEncumbranceCancelReversalCredit: tranCode(id: "b7976c0e-2e4c-4e99-a48f-86384f3dddf6") {
    ...TC
  }
  achEncumbranceCredit: tranCode(id: "8fe41dca-190a-4c84-adc9-78952ac70a54") {
    ...TC
  }
  achEncumbranceDebit: tranCode(id: "0b83d0d4-b580-4056-a094-74ef393328b7") {
    ...TC
  }
  achEncumbranceReturnDebit: tranCode(id: "cde02e54-e725-46bc-9b61-5511c93058a7") {
    ...TC
  }
  achEncumbranceReturnCredit: tranCode(id: "4c4d9599-1caa-4632-a6fb-ca1ae3a2b836") {
    ...TC
  }
  achEncumbranceReversalDebit: tranCode(id: "cd7b997c-526c-4b8f-ac56-8c6de009dc25") {
    ...TC
  }
  achEncumbranceReversalCredit: tranCode(id: "f57ba3a2-ccfa-47de-ae81-1a8167639fe3") {
    ...TC
  }
  achFeeDebit: tranCode(id: "d3b64ee6-0815-4d06-aa9b-906bc48cbc19") {
    ...TC
  }
  achFeeReimburseCredit: tranCode(id: "49b0f890-75e7-4b94-920b-54328c02b2ca") {
    ...TC
  }
  achPendingDebit: tranCode(id: "e19dfe3f-6513-425a-b9a3-870f91303cc8") {
    ...TC
  }
  achPendingCancelCredit: tranCode(id: "c66725d7-c115-4339-89e9-69b6a6ae97bd") {
    ...TC
  }
  achPendingCancelReversalDebit: tranCode(id: "f83a1768-06a1-4a6b-a472-6e9b9c7dbe75") {
    ...TC
  }
  achPendingReversalDebit: tranCode(id: "21036f96-bc05-4526-8004-e63ff6955d0a") {
    ...TC
  }
  achSettleCredit: tranCode(id: "d918eb34-1ef9-4437-a82b-46c169f63e41") {
    ...TC
  }
  achSettleDebit: tranCode(id: "5af51352-84ad-4534-aacf-4e68c2ed2e2b") {
    ...TC
  }
  achSettleReturnCredit: tranCode(id: "90e09ed8-ae9c-46f2-9be8-2e09b4a5de35") {
    ...TC
  }
  achSettleReturnDebit: tranCode(id: "2b11b428-54ed-429c-97d9-b9a4e3ef6007") {
    ...TC
  }  
}
fragment TC on TranCode {
  tranCodeId
  code
  description
  params {
    name
    type
    default
    description
  }
  transaction {
    effective
    journalId
    correlationId
    externalId
    description
    metadata
  }
  entries {
    entryType
    accountId
    layer
    direction
    units
    currency
    description
    metadata
    condition
  }
}
