mutation ReferenceSchemaSetup {
  schema {
    transactionCategoryIndex: createIndex(
      input: {
        name: "Transaction.metadata.category"
        on: Transaction
        unique: false
        partition: [{ alias: "category", value: "string(document.metadata.category)" }]
        sort: [{ alias: "category", value: "string(document.metadata.category)", sort: ASC }]
        constraints: { hasCategory: "has(document.metadata.category)" }
      }
    ) {
      name
    }

    accountTypeIndex: createIndex(
      input: {
        name: "Account.metadata.type"
        on: Account
        unique: false
        partition: [{ alias: "type", value: "string(document.metadata.type)" }]
        sort: [{ alias: "type", value: "string(document.metadata.type)", sort: ASC }]
        constraints: { hasCategory: "has(document.metadata.type)" }
      }
    ) {
      name
    }

    accountSetTypeIndex: createIndex(
      input: {
        name: "AccountSet.metadata.type"
        on: AccountSet
        unique: false
        partition: [{ alias: "type", value: "string(document.metadata.type)" }]
        sort: [{ alias: "type", value: "string(document.metadata.type)", sort: ASC }]
        constraints: { hasCategory: "has(document.metadata.type)" }
      }
    ) {
      name
    }
  }
}
