mutation MultiCurrencySetup(
  $journalId: UUID!
  $journalIdExpr: Expression!
  $exchangerAcctId: UUID!
  $fxAcctId: UUID!
  $fxAcctIdExpr: Expression!
) {
  gl: createJournal(
    input: { journalId: $journalId, name: "GL", description: "General Ledger" }
  ) {
    journalId
  }

  exchanger: createAccount(
    input: {
      accountId: $exchangerAcctId
      code: "USER_A"
      name: "User A"
      description: "Account for user A"
      normalBalanceType: CREDIT
      status: ACTIVE
    }
  ) {
    accountId
  }

  fx_broker: createAccount(
    input: {
      accountId: $fxAcctId
      code: "FX_BROKER"
      name: "FX Broker"
      description: "Foreign Exchange Broker Account"
      normalBalanceType: CREDIT
      status: ACTIVE
    }
  ) {
    accountId
  }

  fx_tc: createTranCode(
    input: {
      tranCodeId: "a1b795df-0f8d-4f24-85af-b087b7d1db5e"
      code: "FX"
      description: "Foreign exchange"
      params: [
        { name: "effective", type: DATE }
        { name: "account", type: UUID }
        { name: "sellUnits", type: DECIMAL }
        { name: "sellCurrency", type: STRING }
        { name: "buyCurrency", type: STRING }
        { name: "exchangeRate", type: DECIMAL }
      ]
      transaction: { journalId: $journalIdExpr, effective: "params.effective" }
      entries: [
        {
          accountId: "params.account"
          units: "params.sellUnits"
          currency: "params.sellCurrency"
          entryType: "'FX_SELL_DR'"
          direction: "DEBIT"
          layer: "SETTLED"
        }
        {
          accountId: $fxAcctIdExpr
          units: "params.sellUnits"
          currency: "params.sellCurrency"
          entryType: "'FX_SELL_CR'"
          direction: "CREDIT"
          layer: "SETTLED"
        }
        {
          accountId: $fxAcctIdExpr
          units: "decimal.Mul(params.sellUnits, params.exchangeRate)"
          currency: "params.buyCurrency"
          entryType: "'FX_BUY_DR'"
          direction: "DEBIT"
          layer: "SETTLED"
        }
        {
          accountId: "params.account"
          units: "decimal.Mul(params.sellUnits, params.exchangeRate)"
          currency: "params.buyCurrency"
          entryType: "'FX_BUY_CR'"
          direction: "CREDIT"
          layer: "SETTLED"
        }
      ]
    }
  ) {
    tranCodeId
  }
}
