mutation TranCodeLibrarySeed {
  generalLedger: createJournal(
    input: {
      journalId: "8345d4a6-e100-4f70-9a31-d458acb3553e"
      name: "GL"
      description: "General Ledger"
    }
  ) {
    journalId
  }
}