mutation PostTXs {
  tx_1: postTransaction(
    input: {
      transactionId: "5c328550-bba3-423b-a58a-b3f9786a80ad"
      tranCode: "ACH_CREDIT"
      params: {
        account: "260fd651-8819-4f99-9c8a-87d27e03ee4c"
        amount: "10.25"
        effective: "2022-09-08"
      }
    }
  ) {
    transactionId
  }

  tx_2: postTransaction(
    input: {
      transactionId: "cd48f439-1f7b-40aa-9b95-4fcbbb51e3cf"
      tranCode: "ACH_CREDIT"
      params: {
        account: "ae9d36cb-dcf5-41a9-bc1e-99a1cf56ef5b"
        amount: "31.72"
        effective: "2022-09-09"
      }
    }
  ) {
    transactionId
  }
}
