mutation BasicTransaction {
  postTransaction(input: {
    transactionId: "a71dd074-3b4e-465b-80f4-9dc111a8ecb4"
    tranCode: "ACH_CREDIT"
    params: {
      account: "63e766a5-4a04-4aee-a4d6-aa49350f13c6"
      amount: "12.87"
      effectiveDate: "2022-09-21"
    }
  }) {
    transactionId
    tranCode {
      code
    }
    entries(first: 4) {
      nodes {
        accountId
        units
        currency
        direction
        layer
      }
    }
  }
}
