query GetSchemaIndexes {
  schema {
    indexes(first: 10) {
      nodes {
        name
        range {
          alias
          value
          sort
        }
        partition {
          alias
          value
        }
        on
        constraints
        unique
      }
    }
  }
}
