mutation PostACHWithdrawal {
  postTransaction(
    input: {
      transactionId: "39d2288d-96f9-40c7-b587-e7e75df083fa"
      tranCode: "ACH_DEBIT"
      params: {
        account: "1fd1dd3e-33fe-4ef5-9d58-676ef8d306b5"
        amount: "4.28"
        effective: "2022-09-21"
      }
    }
  ) {
    transactionId
    tranCodeId
    effective
    entries(first: 2) {
      nodes {
        units
        direction
        account {
          name
        }
      }
    }
  }
}
