mutation CreateAssetsAccount {
  createAccount(
    input: {
      accountId: "78551b96-9c34-46f9-8d5f-c86e4459fcd7"
      name: "Assets"
      code: "ASSET"
      description: "Zuzu's assets (e.g. cash deposits)"
      normalBalanceType: DEBIT
    }
  ) {
    accountId
    name
    normalBalanceType
  }
}
