query AccountSetEntries {
  acct_set_1: accountSet(id: "861f2709-5e62-4a97-8364-b4d3b0a3b31f") {
    members(first: 10) {
      nodes {
        ...on Account {
          accountId
        }
      }
    }
    entries(first: 20) {
      nodes {
        journalId
        accountId
        entryType
        layer
        direction
        units
        currency
      }
    }
    balance(currency: "USD") {
      journalId
      settled {
        normalBalance {
          units
        }
        drBalance {
          units
        }
        crBalance {
          units
        }
      }
    }
  }

  acct_set_2: accountSet(id: "c21f202f-d92d-48e5-aaf0-d48865a98051") {
    journalId
    members(first: 10) {
      nodes {
        ...on Account {
          accountId
        }
      }
    }
    entries(first: 20) {
      nodes {
        journalId
        accountId
        entryType
        layer
        direction
        units
        currency
      }
    }
    balance(currency: "USD") {
      journalId
      settled {
        normalBalance {
          units
        }
        drBalance {
          units
        }
        crBalance {
          units
        }
      }
    }
  }
}
