query GetAccounts {
  accounts(index: { name: CODE }, where: { code: { like: "CUST." } }, first: 2) {
    nodes {
      accountId
      code
      name
      description
      normalBalanceType
      status
    }
  }
}
