query listTables {
  warehouse {
    listTables(
      input: {
        maxResults: 5
        database: "twisp"
        schemaPattern: "public"
      }
    ) {
      tables {
        name
      }
    }
  }
}
