mutation CardTranCodes(
  $cardHold: TranCodeInput!
  $cardHoldVoid: TranCodeInput!
  $cardHoldReplace: TranCodeInput!
  $cardSettle: TranCodeInput!
  $cardDecline: TranCodeInput!
){
  cardHold:createTranCode(
    input: $cardHold
  ) {
    ...TC
  }

  cardHoldVoid:createTranCode(
    input: $cardHoldVoid
  ) {
    ...TC
  }

  cardHoldReplace: createTranCode(
    input: $cardHoldReplace
  ) {
    ...TC
  }

  cardSettle: createTranCode(
    input: $cardSettle
  ) {
    ...TC
  }

  cardDecline: createTranCode(
    input: $cardDecline
  ) {
    ...TC
  }
}

fragment TC on TranCode {
  tranCodeId
  code
  description
  params {
    name
    type
    default
    description
  }
  transaction {
    effective
    journalId
    correlationId
    externalId
    description
    metadata
  }
  entries {
    entryType
    accountId
    layer
    direction
    units
    currency
    description
    metadata
    condition
  }
}
