mutation PostACHDebit(
  $userAcctId: UUID!
  $amount: String!
  $effective: String!
) {
  postTransaction(
    input: {
      transactionId: "7aae6811-3ae1-4d48-9d41-0b4d6fae91a2"
      tranCode: "ACH_DEBIT"
      params: {
        account: $userAcctId
        amount: $amount
        effective: $effective
      }
    }
  ) {
    transactionId
    tranCode {
      code
    }
    effective
    entries(first: 2) {
      nodes {
        amount {
          money: formatted(as: { locale: "en-US" })
        }
        direction
        layer
        account {
          name
        }
      }
    }
  }
}
